export const runtime='nodejs';
import{gateway}from'../../../lib/gateway';
function cleanHtml(s){return String(s||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<noscript\b[^>]*>[\s\S]*?<\/noscript>/gi,' ')}
function decode(s){return s.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n))}
function textLines(html){let h=cleanHtml(html);const main=h.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i)?.[1]||h;h=main.replace(/<\/?(?:nav|footer|header)\b[^>]*>/gi,' ');h=h.replace(/<(?:br|\/p|\/li|\/h[1-6]|\/tr|\/div|\/section|\/details|\/summary|\/td|\/th)>/gi,'\n').replace(/<[^>]+>/g,' ');return decode(h).split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(x=>x.length>=3&&x.length<=500)}
function jsonld(html){const out=[];for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const j=JSON.parse(m[1]);const walk=x=>{if(!x||typeof x!=='object')return;if(Array.isArray(x))return x.forEach(walk);out.push(x);if(x['@graph'])walk(x['@graph'])};walk(j)}catch{}}return out}
function typeIs(x,t){const a=x?.['@type'];return Array.isArray(a)?a.includes(t):a===t}
function titleFrom(html,nodes){const p=nodes.find(x=>typeIs(x,'Product'));return p?.name||decode(html.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i)?.[1]||html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'').replace(/\s*[|–—-]\s*[^|–—-]+$/,'').trim()}
function reviewCount(html,nodes){const p=nodes.find(x=>typeIs(x,'Product')),a=p?.aggregateRating;for(const v of[a?.reviewCount,a?.ratingCount]){const n=parseInt(String(v||'').replace(/[^0-9]/g,''),10);if(Number.isFinite(n)&&n>=0)return n}const pats=[/data-(?:product-)?reviews?-count=["']([\d,]+)["']/i,/data-review-count=["']([\d,]+)["']/i,/data-rating-count=["']([\d,]+)["']/i,/data-raters=["']([\d,]+)["']/i,/["'](?:reviewCount|review_count|reviews_count|total_reviews|totalReviews|ratingCount)["']\s*[:=]\s*["']?([\d,]+)/i,/class=["'][^"']*(?:jdgm-rev-widg__summary-text|spr-summary-caption|stamped-summary-caption|yotpo-bottomline|loox-rating|areviews)[^"']*["'][^>]*>[\s\S]{0,400}?([\d,]+)\s+(?:verified\s+|customer\s+)?reviews?/i,/([\d,]+)\s+(?:verified\s+|customer\s+)?reviews?\b/i];for(const re of pats){const m=html.match(re);if(m){const n=parseInt(m[1].replace(/,/g,''),10);if(Number.isFinite(n)&&n>=0)return n}}return null}
function obviousNoise(x){return /^(?:add to cart|buy now|checkout|quantity|sold out|unavailable|share|search|menu|account|cart|home|shop|subscribe|newsletter)$/i.test(x)||/(?:free shipping|shipping calculated|returns?|refund|money.?back|warranty|guarantee|shop pay|klarna|afterpay|affirm|sale price|regular price|save \d+%|reviews?\s*\(\d+\)|write a review)/i.test(x)}
function parseIds(text,max){const a=String(text).match(/\[[\s\S]*?\]/)?.[0];if(!a)throw Error('AI cleanup returned an invalid line selection.');const ids=JSON.parse(a);if(!Array.isArray(ids))throw Error('AI cleanup returned an invalid line selection.');return[...new Set(ids.map(Number).filter(n=>Number.isInteger(n)&&n>=1&&n<=max))]}
async function selectLines(req,lines){const numbered=lines.map((x,i)=>`${i+1}. ${x}`).join('\n');const prompt=`Select a VERY SMALL set of exact product-page lines for an internal synthetic consumer-text QA dataset. Return ONLY a JSON array of line numbers, ordered from most useful to least useful. Keep AT MOST 10 lines. Do not rewrite anything.\n\nThe goal is NOT to preserve the full product description. Keep only consumer-relevant product context that would be useful when testing review-like UI text, search, summarization, moderation, or rating displays.\n\nPrioritize: what the product is/does; main use case; a few noticeable benefits or limitations; setup when it affects usability; size/material/compatibility only when it materially affects the user experience.\n\nAggressively EXCLUDE: engineering specs; frequency ranges; electrical values; model numbers; certifications; regulatory language; exhaustive measurements; dense technical tables; obscure compatibility details; exhaustive included-parts lists; marketing superlatives; repetitive claims; pricing/payment; promos; shipping/returns; warranty; review/social-proof copy; navigation/UI; generic brand/store fluff. If a detail is too technical or peripheral to be useful in natural consumer-text QA, leave it out.\n\nLINES:\n${numbered}`;const r=await gateway(req,prompt,60000);return parseIds(r.text,lines.length)}
export async function POST(req){try{const{url}=await req.json();if(!url)throw Error('Product URL is required.');const u=new URL(/^https?:\/\//i.test(url)?url:'https://'+url);const r=await fetch(u,{headers:{'user-agent':'Mozilla/5.0 SyntheticReviewLab/1.0','accept':'text/html'},redirect:'follow',signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`Product page returned HTTP ${r.status}.`);const html=await r.text(),nodes=jsonld(html),title=titleFrom(html,nodes);let lines=textLines(html).filter(x=>!obviousNoise(x));lines=[...new Set(lines)].slice(0,220);if(!title)throw Error('Could not identify the product title.');if(!lines.length)throw Error('No useful product-page text was found.');const ids=await selectLines(req,lines);const technical=/(?:\b(?:vswr|mhz|ghz|ohm|dbi|decibel|impedance|voltage|amperage|fcc|ul listed|ce certified|frequency range|operating frequency)\b|\b\d{2,5}\s*(?:mhz|ghz|ohms?|dbi|volts?|amps?)\b)/i;const selected=ids.map(i=>lines[i-1]).filter(x=>!technical.test(x)).slice(0,10);if(!selected.length)throw Error('AI cleanup did not find naturally reviewable product details.');return Response.json({productUrl:r.url,productTitle:title,productDescription:selected.join('\n').slice(0,4500),extracted:{lines:selected.length,candidateLines:lines.length,contextChars:selected.join('\n').length,existingReviewCount:reviewCount(html,nodes),cleanup:'AI consumer-context QA selection'}})}catch(e){return Response.json({error:e.message||'Scan failed.'},{status:400})}}
