import{createHash,timingSafeEqual}from'node:crypto';
export const runtime='nodejs';export const dynamic='force-dynamic';export const maxDuration=300;
const HASH='f2584fb0fe31bcad29bf49c42ce24b68d40a56025c2b427baa6db6696334d807';
const EXPIRES=Date.parse('2026-09-12T12:00:00Z');
const STORE='https://plcqypajqvtpnjctdlho.supabase.co/functions/v1/blvckledge-archive-store';
const PROFILE='https://site.twstalker.com/blvckledge',TARGET='https://site.twstalker.com/service/api',ZONE='synthetic_review_ebay_items',AUTHOR='blvckledge';
const SOURCE_JOB='blvckledge-archive-'+createHash('sha256').update(AUTHOR).digest('hex').slice(0,32);
const H={'cache-control':'private, no-store','x-robots-tag':'noindex'};const hash=x=>createHash('sha256').update(String(x)).digest('hex');const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function auth(req){const p=new URL(req.url).searchParams,t=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||p.get('ticket')||'';return t&&Date.now()<EXPIRES&&timingSafeEqual(Buffer.from(hash(t),'hex'),Buffer.from(HASH,'hex'))?t:null}
function clean(v){return String(v||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/[ \t]+/g,' ').trim()}
function pid(v){const s=String(v??'');return /^\d{8,24}$/.test(s)?s:null}
function rows(body,page){const e=body&&typeof body==='object'&&body.tweets?Object.entries(body.tweets):[],out=[];for(const[idKey,t]of e){const id=pid(idKey)||pid(t?.id_str)||pid(t?.id);if(!id)continue;const a=String(t?.core?.screen_name||'').replace(/^@/,'');if(a.toLowerCase()!==AUTHOR)continue;const d=t?.created_at,iso=d&&Number.isFinite(Date.parse(d))?new Date(d).toISOString():null,conv=pid(t?.conversation_id_str)||pid(t?.conversation_id);out.push({id,source_job:SOURCE_JOB,author_handle:AUTHOR,is_authored_by_target:true,content_kind:t?.is_retweet?'repost':conv&&conv!==id?'reply':t?.is_quote_status?'quote_post':'post',text:clean(t?.full_text||t?.text||''),url:'https://x.com/'+AUTHOR+'/status/'+id,published_at:iso,parent_post_id:null,conversation_id:conv,article_urls:[],raw:{...t,id_str:id,mirror_page:page,mirror_source:'twstalker_via_bright_data',target:AUTHOR}})}return out}
export async function GET(req){const token=auth(req);if(!token)return new Response('Not found',{status:404});const key=process.env.BRIGHT_DATA_API_KEY||'';const p=new URL(req.url).searchParams;
 async function store(op,b={}){const r=await fetch(STORE,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({op,...b}),cache:'no-store',signal:AbortSignal.timeout(45000)}),t=await r.text();if(!r.ok)throw Error('Storage '+r.status+': '+t.slice(0,500));return t?JSON.parse(t):null}
 async function up(path,body){const r=await fetch('https://api.brightdata.com'+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer '+key,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),cache:'no-store',signal:AbortSignal.timeout(95000)}),t=await r.text();let v;try{v=JSON.parse(t)}catch{v=t}return{status:r.status,value:v}}
 async function patch(id,patch){return store('patch',{id,patch})}
 async function save(rs){for(let i=0;i<rs.length;i+=100)await store('save_posts',{rows:rs.slice(i,i+100)})}
 async function poll(job){const r=await up('/unblocker/get_result?response_id='+encodeURIComponent(job.diagnostics.response_id));if(r.status===202)return{status:'running',page:job.request.page||0};let body=r.value?.body??r.value;if(typeof body==='string'){try{body=JSON.parse(body)}catch{}}
   if(job.request.mode==='mirror_seed'){const html=typeof body==='string'?body:String(body?.body||body||''),tag=html.match(/<a\b[^>]*class=["'][^"']*add-nw-event[^"']*["'][^>]*>/i)?.[0]||'',profileId=tag.match(/data-query=["'](\d+)["']/i)?.[1]||null,cursor=tag.match(/data-cursor=["']([^"']+)["']/i)?.[1]||null,page=Number(tag.match(/data-ec=["'](\d+)["']/i)?.[1]||2);const ok=Boolean(profileId&&cursor);await patch(job.id,{status:ok?'complete':'failed',record_count:1,raw_records:[{html}],diagnostics:{...job.diagnostics,profileId,cursor,page,hasMore:ok},...(ok?{}:{error:{message:'Seed parse failed'}})});return{status:ok?'complete':'failed',mode:'seed',profileId,page}}
   const entries=body&&typeof body==='object'&&body.tweets?Object.entries(body.tweets):[],cursor=typeof body?.cursor==='string'?body.cursor:null,rs=rows(body,job.request.page),dates=rs.map(x=>Date.parse(x.published_at)).filter(Number.isFinite).sort((a,b)=>a-b),ok=r.value?.status_code===200||r.status===200;await save(rs);await patch(job.id,{status:ok?'complete':'failed',record_count:entries.length,raw_records:[{response:body}],diagnostics:{...job.diagnostics,postCount:entries.length,authored:rs.length,cursor,hasMore:Boolean(cursor&&cursor!==job.request.cursor&&entries.length),oldest:dates.length?new Date(dates[0]).toISOString():null,newest:dates.length?new Date(dates.at(-1)).toISOString():null}});return{status:ok?'complete':'failed',page:job.request.page,posts:rs.length,oldest:dates.length?new Date(dates[0]).toISOString():null}}
 async function startReq(id,request,body){const q=await store('reserve',{id,request:{...request,target:AUTHOR},max:1});if(!q.created)return q.job;const r=await up('/unblocker/req?zone='+ZONE,body);if(r.status!==200||!r.value?.response_id)throw Error('Bright Data submit failed');await patch(id,{status:'mirror_running',diagnostics:{response_id:r.value.response_id}});return{id,status:'running',request}}
 async function step(){const jobs=await store('list'),pending=jobs.find(j=>j.status==='mirror_running');if(pending)return poll(pending);const seed=jobs.find(j=>j.request?.mode==='mirror_seed'&&j.status==='complete');if(!seed){const id='blv_'+hash('seed:'+AUTHOR).slice(0,32),body={url:PROFILE,method:'GET'};return startReq(id,{mode:'mirror_seed',url:PROFILE,page:0},body)}
   const complete=jobs.filter(j=>j.request?.mode==='mirror_cursor'&&j.status==='complete').sort((a,b)=>(b.request.page||0)-(a.request.page||0));let page,cursor,profileId;if(complete.length){const last=complete[0];if(!last.diagnostics?.hasMore)return{status:'timeline_exhausted',page:last.request.page,oldest:last.diagnostics?.oldest};page=last.request.page+1;cursor=last.diagnostics.cursor;profileId=last.request.profile_id}else{page=seed.diagnostics.page||2;cursor=seed.diagnostics.cursor;profileId=seed.diagnostics.profileId}
   const cfg={mode:'mirror_cursor',page,cursor,profile_id:profileId,url:TARGET};const id='blv_'+hash(JSON.stringify(cfg)).slice(0,32),form=new URLSearchParams({page:String(page),cursor,data:String(profileId),action:'profile'}).toString(),body={url:TARGET,method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8',Referer:PROFILE,Origin:'https://site.twstalker.com','X-Requested-With':'XMLHttpRequest'},body:form};return startReq(id,cfg,body)}
 try{const op=p.get('op')||'status';if(op==='advance')return Response.json(await step(),{headers:H});if(op==='run'){const until=Date.now()+220000,res=[];let pages=0;while(Date.now()<until&&pages<10){const s=await step();res.push(s);if(s.status==='complete'&&s.page)pages++;if(['timeline_exhausted','failed'].includes(s.status))break;await sleep(s.status==='running'?3500:250)}return Response.json({pages,res},{headers:H})}const jobs=await store('list');return Response.json({sourceJob:SOURCE_JOB,jobs:jobs.map(j=>({mode:j.request?.mode,page:j.request?.page,status:j.status,posts:j.diagnostics?.authored,oldest:j.diagnostics?.oldest,newest:j.diagnostics?.newest,hasMore:j.diagnostics?.hasMore,profileId:j.diagnostics?.profileId}))},{headers:H})}catch(e){return Response.json({error:String(e?.message||e).split(key).join('[REDACTED]').slice(0,1200)},{status:502,headers:H})}}
export async function POST(req){return GET(req)}