import { createHash, timingSafeEqual } from 'node:crypto';
export const runtime='nodejs';
export const dynamic='force-dynamic';
export const maxDuration=300;

const HASH='eeb803ca9122d1d9568f48ba0f36938c2907894d25f455d2a10edb7985b95e4f';
const EXPIRES=Date.parse('2026-09-12T12:00:00Z');
const STORE='https://plcqypajqvtpnjctdlho.supabase.co/functions/v1/marketing-article-store';
const BEARER='Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA';
const QUERY='HJ9lpOL-ZlOk5CkCw0JW6Q';
const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36';
const H={'cache-control':'private, no-store','x-robots-tag':'noindex','referrer-policy':'no-referrer'};
const hash=x=>createHash('sha256').update(String(x)).digest('hex');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const FEATURES={creator_subscriptions_tweet_preview_api_enabled:true,premium_content_api_read_enabled:false,communities_web_enable_tweet_community_results_fetch:true,c9s_tweet_anatomy_moderator_badge_enabled:true,responsive_web_grok_analyze_button_fetch_trends_enabled:false,responsive_web_grok_analyze_post_followups_enabled:true,responsive_web_jetfuel_frame:false,responsive_web_grok_share_attachment_enabled:true,responsive_web_grok_annotations_enabled:true,articles_preview_enabled:true,responsive_web_edit_tweet_api_enabled:true,graphql_is_translatable_rweb_tweet_is_translatable_enabled:true,view_counts_everywhere_api_enabled:true,longform_notetweets_consumption_enabled:true,responsive_web_twitter_article_tweet_consumption_enabled:true,tweet_awards_web_tipping_enabled:false,responsive_web_grok_show_grok_translated_post:false,responsive_web_grok_analysis_button_from_backend:true,post_ctas_fetch_enabled:false,creator_subscriptions_quote_tweet_preview_enabled:false,freedom_of_speech_not_reach_fetch_enabled:true,standardized_nudges_misinfo:true,tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled:true,longform_notetweets_rich_text_read_enabled:true,longform_notetweets_inline_media_enabled:true,profile_label_improvements_pcf_label_in_post_enabled:true,responsive_web_profile_redirect_enabled:true,rweb_tipjar_consumption_enabled:true,verified_phone_label_enabled:false,responsive_web_grok_image_annotation_enabled:true,responsive_web_grok_imagine_annotation_enabled:true,responsive_web_grok_community_note_auto_translation_is_enabled:true,responsive_web_graphql_skip_user_profile_image_extensions_enabled:false,responsive_web_graphql_timeline_navigation_enabled:true,responsive_web_enhance_cards_enabled:false};
const TOGGLES={withArticleRichContentState:true,withArticlePlainText:true,withGrokAnalyze:false,withDisallowedReplyControls:false,withPayments:true,withAuxiliaryUserLabels:true};

function articleFrom(payload){const r=payload?.data?.tweetResult?.result;const t=r?.tweet||r;return t?.article?.article_results?.result||t?.legacy?.article?.article_results?.result||null}
function normalizeEntityMap(v){if(Array.isArray(v))return new Map(v.map((e,i)=>[String(e?.key??i),e]));if(v&&typeof v==='object')return new Map(Object.entries(v));return new Map()}
function mdInline(text,ranges,emap){if(!text)return'';const rs=(Array.isArray(ranges)?ranges:[]).filter(r=>Number.isInteger(r?.offset)&&Number.isInteger(r?.length)&&r.length>0).sort((a,b)=>b.offset-a.offset);let out=text;for(const r of rs){const ent=emap.get(String(r.key));const url=ent?.data?.url||ent?.data?.href||ent?.data?.link_url||ent?.url;const start=r.offset,end=start+r.length;if(start<0||end>out.length||!url)continue;out=out.slice(0,start)+'['+out.slice(start,end)+']('+url+')'+out.slice(end)}return out}
function markdown(content){const blocks=Array.isArray(content?.blocks)?content.blocks:[],emap=normalizeEntityMap(content?.entity_map??content?.entityMap);const lines=[];for(const b of blocks){const t=mdInline(String(b?.text||''),b?.entity_ranges??b?.entityRanges,emap),type=String(b?.type||'unstyled');if(type==='header-one')lines.push('# '+t);else if(type==='header-two')lines.push('## '+t);else if(type==='header-three')lines.push('### '+t);else if(type==='header-four')lines.push('#### '+t);else if(type==='unordered-list-item')lines.push('- '+t);else if(type==='ordered-list-item')lines.push('1. '+t);else if(type==='blockquote')lines.push('> '+t);else if(type==='code-block')lines.push('```\n'+t+'\n```');else lines.push(t)}return lines.join('\n\n').replace(/\n{3,}/g,'\n\n').trim()}
function mediaUrls(a){const s=JSON.stringify({cover:a?.cover_media,media:a?.media_entities});const matches=s.match(/https:\/\/pbs\.twimg\.com\/[^"\\]+/g)||[];return [...new Set(matches.map(x=>x.replace(/\\u002F/g,'/').replace(/\\\//g,'/')))]}
function words(s){return String(s||'').trim()?String(s).trim().split(/\s+/).length:0}

export async function GET(req){
 const q=new URL(req.url).searchParams,token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||q.get('ticket')||'';
 const ok=token&&Date.now()<EXPIRES&&timingSafeEqual(Buffer.from(hash(token),'hex'),Buffer.from(HASH,'hex'));
 if(!ok)return new Response('Not found',{status:404});
 const op=q.get('op')||'status',limit=Math.max(1,Math.min(Number(q.get('limit')||48),100));
 async function store(operation,payload={}){const r=await fetch(STORE,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({op:operation,payload}),cache:'no-store',signal:AbortSignal.timeout(30000)});const t=await r.text();if(!r.ok)throw new Error('store '+r.status+': '+t.slice(0,600));return t?JSON.parse(t):null}
 async function guest(){const r=await fetch('https://api.x.com/1.1/guest/activate.json',{method:'POST',headers:{authorization:BEARER,'user-agent':UA},signal:AbortSignal.timeout(30000)});const j=await r.json();if(!r.ok||!j.guest_token)throw new Error('guest '+r.status);return j.guest_token}
 async function fetchOne(src,gt){const u=new URL(`https://x.com/i/api/graphql/${QUERY}/TweetResultByRestId`);u.searchParams.set('variables',JSON.stringify({tweetId:src.source_post_id,withCommunity:false,includePromotedContent:false,withVoice:true}));u.searchParams.set('features',JSON.stringify(FEATURES));u.searchParams.set('fieldToggles',JSON.stringify(TOGGLES));const r=await fetch(u,{headers:{authorization:BEARER,'x-guest-token':gt,'user-agent':UA,accept:'application/json','x-twitter-active-user':'yes','x-twitter-client-language':'en'},signal:AbortSignal.timeout(60000)});const tx=await r.text();let data;try{data=JSON.parse(tx)}catch{throw new Error('invalid json '+r.status)}if(!r.ok)throw new Error('x '+r.status+': '+JSON.stringify(data?.errors||data).slice(0,300));const a=articleFrom(data);if(!a)throw new Error('article missing');const rid=String(a.rest_id||'');if(rid&&rid!==String(src.article_id))throw new Error('article id mismatch');const body=String(a.plain_text||'').trim(),md=markdown(a.content_state);if(body.length<50)throw new Error('article body too short');return{article_id:String(src.article_id),author_handle:String(src.author_handle),title:String(a.title||'').trim(),body,body_markdown:md||body,body_html:null,media_urls:mediaUrls(a),raw:{article:a,source_post_id:src.source_post_id,article_url:src.url,wrapper_published_at:src.published_at,query:'TweetResultByRestId'},extraction_status:'complete',extraction_method:'x_guest_graphql_tweet_result',word_count:words(body),quality_notes:'Full plain_text captured; Draft.js content_state preserved in raw.'}}
 if(op==='status')return Response.json(await store('audit'),{headers:H});
 if(op!=='run')return Response.json({error:'invalid op'},{status:400,headers:H});
 const pending=await store('list_pending',{limit});if(!Array.isArray(pending)||!pending.length)return Response.json({processed:0,audit:await store('audit')},{headers:H});
 const began=Date.now(),results=[];let saved=0;
 for(let i=0;i<pending.length;i+=8){let gt=await guest();const group=pending.slice(i,i+8);const rows=await Promise.all(group.map(async src=>{for(let attempt=0;attempt<2;attempt++){try{return await fetchOne(src,gt)}catch(e){if(attempt===0&&/x 429|x 401|x 403/.test(String(e?.message||e))){gt=await guest();await sleep(250);continue}return{article_id:String(src.article_id),author_handle:String(src.author_handle),extraction_status:'retry',extraction_method:'x_guest_graphql_tweet_result',quality_notes:String(e?.message||e).slice(0,500),raw:{error:String(e?.message||e).slice(0,500),source_post_id:src.source_post_id}}}}}));await store('save',{rows});saved+=rows.filter(r=>r.extraction_status==='complete').length;results.push(...rows.map(r=>({article_id:r.article_id,author:r.author_handle,status:r.extraction_status,chars:(r.body||'').length,words:r.word_count||0,note:r.quality_notes})));await sleep(300)}
 return Response.json({processed:pending.length,saved,elapsedMs:Date.now()-began,results,audit:await store('audit')},{headers:H});
}
export async function POST(req){return GET(req)}
