export const runtime='nodejs';
export const maxDuration=180;
import{gatewayToken}from'../../../lib/gateway';
import{extractReviews,ingestReviewsFromPage,isAmazonUrl,amazonAsin}from'../../../lib/review-ingest';
import{referenceBudget,selectDiverseCandidates,uniqueReferences}from'../../../lib/reference-pipeline.mjs';

const BD='https://api.brightdata.com/request',ZONE=process.env.BRIGHT_DATA_SERP_ZONE||'serp_api1',MODEL='openai/gpt-5.6-sol',GW='https://ai-gateway.vercel.sh/v1/responses',UA='Mozilla/5.0 (compatible; SyntheticReviewLab/1.0; +internal QA reference discovery)';
const BLOCK=/(^localhost$|\.local$|^0\.|^10\.|^127\.|^169\.254\.|^192\.168\.|^172\.(?:1[6-9]|2\d|3[01])\.|^\[?::1\]?$)/i;
function url(x,b){try{const u=new URL(String(x||'').replace(/&amp;/g,'&'),b);return /^https?:$/.test(u.protocol)&&!BLOCK.test(u.hostname)?u:null}catch{return null}}
function text(x){return String(x||'').replace(/<[^>]+>/g,' ').replace(/&(?:nbsp|amp|quot|#39|apos);/gi,' ').replace(/\s+/g,' ').trim()}
function host(x){try{return new URL(x).hostname.replace(/^www\./,'').toLowerCase()}catch{return''}}
function can(x){try{const u=new URL(x);u.hash='';for(const k of[...u.searchParams.keys()])if(/^utm_/i.test(k)||/^(fbclid|gclid|ref|tag|psc)$/i.test(k))u.searchParams.delete(k);if(/(^|\.)google\./i.test(u.hostname)){const z=url(u.searchParams.get('url')||u.searchParams.get('q'));if(z)return can(z.href)}return u.href}catch{return String(x||'')}}
function n(x){const v=Number(String(x??'').replace(/[^0-9.]/g,''));return Number.isFinite(v)&&v>=0?v:null}
function count(x){if(x==null||Array.isArray(x))return null;const m=String(x).toLowerCase().replace(/,/g,'').match(/([0-9]+(?:\.[0-9]+)?)\s*([kmb])?/);if(!m)return null;let v=Number(m[1]);v*=m[2]==='k'?1e3:m[2]==='m'?1e6:m[2]==='b'?1e9:1;return Number.isFinite(v)&&v<=1e9?Math.round(v):null}
function conf(x){return x>=.82?'high':x>=.65?'medium':x>=.5?'low':'none'}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36).toUpperCase()}
function sent(s){return Math.max(1,(String(s).match(/[.!?]+(?:\s|$)/g)||[]).length)}
function scripts(h){const a=[];for(const m of String(h).matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)){const s=m[1].trim();if(s.length>2500000)continue;try{a.push(JSON.parse(s))}catch{}}return a}
function walk(x,f,seen=new Set()){if(!x||typeof x!=='object'||seen.has(x))return;seen.add(x);f(x);for(const v of Array.isArray(x)?x:Object.values(x))walk(v,f,seen)}
async function html(x,t=16000){const u=url(x);if(!u)throw Error('invalid_public_url');const r=await fetch(u,{headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(t)}),h=await r.text();if(r.status===403||r.status===429||/captcha|robot check|verify you are human|access denied|hold button/i.test(h.slice(0,7000)))throw Error('blocked_or_challenged');if(!r.ok)throw Error(`http_${r.status}`);return{h,u:r.url}}
function images(h,b,maxImages=1){const a=[],add=x=>{if(Array.isArray(x))return x.forEach(add);if(x&&typeof x==='object')return add(x.url||x.contentUrl);const u=url(x,b);if(!u||/(logo|icon|favicon|sprite|payment|badge)/i.test(u.href)||a.includes(u.href))return;a.push(u.href)};for(const m of String(h).matchAll(/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)/gi))add(m[1]);for(const j of scripts(h))walk(j,o=>{const t=o?.['@type'];if(t==='Product'||Array.isArray(t)&&t.includes('Product'))add(o.image)});for(const m of String(h).matchAll(/<meta[^>]+name=["']twitter:image["'][^>]+content=["']([^"']+)/gi))add(m[1]);for(const m of String(h).matchAll(/<img[^>]+(?:data-src|src)=["']([^"']+)/gi))add(m[1]);return a.slice(0,Math.max(1,maxImages))}
function pageTitle(h){return text(String(h).match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i)?.[1]||String(h).match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'')}
function reviewCount(h){let best=null,take=x=>{const v=count(x);if(v!=null)best=best==null?v:Math.max(best,v)};for(const j of scripts(h))walk(j,o=>{if(!o||typeof o!=='object')return;take(o.aggregateRating?.reviewCount);take(o.aggregateRating?.ratingCount);for(const k of['reviewCount','review_count','reviews_count','total_reviews','totalReviews','ratingCount','ratingsCount'])take(o[k])});for(const re of[/([\d,.]+)\s+(?:verified\s+|customer\s+)?reviews?\b/i,/([\d,.]+)\s+ratings?\b/i]){const m=String(h).match(re);if(m)take(m[1])}return best}
async function imgData(x){if(/^data:image\//i.test(String(x||'')))return String(x).length<5e6?String(x):null;const u=url(x);if(!u)return null;try{const r=await fetch(u,{headers:{'user-agent':UA,'accept':'image/*'},redirect:'follow',signal:AbortSignal.timeout(10000)});if(!r.ok)return null;const ct=(r.headers.get('content-type')||'').split(';')[0],b=Buffer.from(await r.arrayBuffer());return ct.startsWith('image/')&&ct!=='image/svg+xml'&&b.length<3e6?`data:${ct};base64,${b.toString('base64')}`:null}catch{return null}}

async function lens(tab,image,key){const q=`https://lens.google.com/uploadbyurl?url=${encodeURIComponent(image)}&brd_json=1&brd_lens=${tab}&hl=en&gl=US`,r=await fetch(BD,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({zone:ZONE,url:q,format:'raw'}),signal:AbortSignal.timeout(65000)}),raw=await r.text();if(!r.ok)throw Error(`bright_data_${tab}_${r.status}:${raw.slice(0,150)}`);let j;try{j=JSON.parse(raw);if(typeof j==='string')j=JSON.parse(j)}catch{throw Error(`bright_data_${tab}_invalid_json`)}return j}
function itemUrl(o){for(const x of[o?.product_link,o?.merchant_link,o?.page_url,o?.source_url,o?.link,o?.url]){const u=url(x);if(!u)continue;if(/(^|\.)google\./i.test(u.hostname)){const z=url(u.searchParams.get('url')||u.searchParams.get('q'));if(z)return z.href;continue}return u.href}return null}
function itemImage(o){for(const x of[o?.image_base64,o?.image,o?.image_url,o?.thumbnail_url,o?.thumbnail])if(typeof x==='string'&&(/^data:image\//i.test(x)||url(x)))return x;return null}
function lensRows(tab,j,imageIndex){const lists=[];if(tab==='exact_matches'&&Array.isArray(j.exact_matches))lists.push(j.exact_matches);if(tab==='products'&&Array.isArray(j.products))lists.push(j.products);if(tab==='products'&&Array.isArray(j.images))lists.push(j.images);if(tab==='visual_matches'&&Array.isArray(j.visual_matches))lists.push(j.visual_matches);if(tab==='visual_matches'&&Array.isArray(j.images))lists.push(j.images);const score=tab==='exact_matches'?.96:tab==='products'?.84:.62,out=[];for(const list of lists)for(const o of list){const u=itemUrl(o);if(!u)continue;out.push({u:can(u),tab,imageIndex,score,rank:Number(o.global_rank||o.rank)||null,title:text(o.title||o.name||''),merchant:text(o.source||o.merchant||o.seller||''),image:itemImage(o),publicCount:count(o.review_count??o.reviews_count??o.rating_count??o.reviews),rating:n(o.rating??o.rating_value??o.stars)})}return out}
function dedupe(rows,sourceHost,maxCandidates=24){const m=new Map();for(const r of rows){if(!r.u||host(r.u)===sourceHost)continue;const asin=isAmazonUrl(r.u)?amazonAsin(r.u):null,k=asin?`a:${asin}`:can(r.u),old=m.get(k)||{u:asin?`https://${url(r.u).hostname}/dp/${asin}`:can(r.u),asin,tabs:new Set(),images:new Set(),score:0,rank:999,title:'',merchant:'',image:null,publicCount:null,rating:null};old.tabs.add(r.tab);old.images.add(r.imageIndex);if(r.score>old.score){old.score=r.score;old.rank=r.rank||999;old.title=r.title;old.merchant=r.merchant;old.image=r.image||old.image}if(old.publicCount==null&&r.publicCount!=null)old.publicCount=r.publicCount;if(old.rating==null&&r.rating!=null&&r.rating<=5)old.rating=r.rating;m.set(k,old)}const unique=[...m.values()].map(x=>({...x,tabs:[...x.tabs],imageHits:x.images.size}));return selectDiverseCandidates(unique,{limit:maxCandidates,maxPerHost:4})}

function modelText(j){if(typeof j?.output_text==='string')return j.output_text;for(const o of j?.output||[])for(const c of o?.content||[])if(typeof c?.text==='string')return c.text;return''}
function obj(s){s=String(s||'').replace(/```(?:json)?/gi,'').replace(/```/g,'');const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a<0||b<a)throw Error('invalid_model_json');return JSON.parse(s.slice(a,b+1))}
async function ai(req,body,timeout=65000){const token=gatewayToken(req);if(!token)throw Error('no_ai_gateway_credential');const r=await fetch(GW,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({model:MODEL,store:false,...body}),signal:AbortSignal.timeout(timeout)}),raw=await r.text();let j;try{j=JSON.parse(raw)}catch{j=null}if(!r.ok)throw Error(j?.error?.message||raw.slice(0,250));return{j,p:obj(modelText(j))}}
async function verify(req,title,desc,sourceImages,candidates){const refs=(await Promise.all(sourceImages.slice(0,2).map(imgData))).filter(Boolean),groups=[];for(let i=0;i<candidates.length;i+=6)groups.push(candidates.slice(i,i+6));const settled=await Promise.allSettled(groups.map(async g=>{const ci=await Promise.all(g.map(async x=>({...x,di:await imgData(x.image)}))),legend=ci.map((x,i)=>`${i+1}. ${x.u} | Lens=${x.tabs.join('+')} | rank=${x.rank} | title=${x.title||'n/a'} | merchant=${x.merchant||'n/a'} | source-image-hits=${x.imageHits}`).join('\n'),content=[{type:'input_text',text:`Google Lens already retrieved these listings. Verify SAME PHYSICAL PRODUCT as the reference, including exact private-label/OEM equivalents. Reject similar products, accessories, different models, and non-product/editorial pages. Images are primary evidence. Return ONLY JSON {"rankings":[{"candidate":1,"sameProduct":true,"confidence":0.0,"relation":"exact|private_label|similar|reject","reason":"specific evidence"}]}.\nREFERENCE TITLE: ${title}\nREFERENCE FACTS: ${desc}\nCANDIDATES:\n${legend}`}];for(let i=0;i<refs.length;i++)content.push({type:'input_text',text:`REFERENCE IMAGE ${i+1}`},{type:'input_image',image_url:refs[i],detail:'high'});for(let i=0;i<ci.length;i++)if(ci[i].di)content.push({type:'input_text',text:`CANDIDATE ${i+1} IMAGE`},{type:'input_image',image_url:ci[i].di,detail:'high'});const{p}=await ai(req,{input:[{type:'message',role:'user',content}]});return ci.map((x,i)=>{const r=(p.rankings||[]).find(y=>Number(y.candidate)===i+1)||{},ac=n(r.confidence),same=Boolean(r.sameProduct),exact=x.tabs.includes('exact_matches'),prod=x.tabs.includes('products'),vis=x.tabs.includes('visual_matches');let ok=false,method='rejected';if(same&&exact&&ac>=.55){ok=true;method='lens_exact+ai'}else if(same&&prod&&ac>=.72){ok=true;method='lens_product+ai'}else if(same&&vis&&ac>=.84){ok=true;method='lens_visual+ai'}else if(exact&&!x.di&&(ac==null||ac<.75)){ok=true;method='lens_exact'}return{...x,accepted:ok,method,aiConfidence:ac,aiReason:text(r.reason||'').slice(0,220),matchScore:ok?Math.max(x.score,ac||0):x.score,confidence:conf(Math.max(x.score,ac||0))}})}));const all=[];for(let i=0;i<settled.length;i++){const s=settled[i];if(s.status==='fulfilled')all.push(...s.value);else all.push(...groups[i].map(x=>({...x,accepted:x.tabs.includes('exact_matches'),method:x.tabs.includes('exact_matches')?'lens_exact_verifier_failed':'verification_failed',aiConfidence:null,aiReason:text(s.reason?.message||s.reason).slice(0,180),matchScore:x.score,confidence:conf(x.score)})))}return all}

async function scrape(c,budget){if(isAmazonUrl(c.u))return{...c,directSourceUrl:c.u,title:c.title||'Amazon',status:'aggregate_only',reviews:[],reviewCount:0,publicCount:c.publicCount,aggregateOnly:true,ing:{providers:['amazon'],embedded:0,paginationPagesFetched:0,providerEndpointsFetched:0,blocked:0,failed:0}};try{const p=await html(c.u),pc=reviewCount(p.h);let ing;try{ing=await ingestReviewsFromPage({html:p.h,url:p.u,maxPages:budget.maxPages,maxEndpoints:budget.maxEndpoints})}catch{const reviews=extractReviews(p.h);ing={reviews,diagnostics:{providers:[],embedded:reviews.length,paginationPagesFetched:0,providerEndpointsFetched:0,blocked:0,failed:1}}}return{...c,u:p.u,directSourceUrl:p.u,title:pageTitle(p.h)||c.title,status:'found',reviews:ing.reviews,reviewCount:ing.reviews.length,publicCount:pc??c.publicCount,aggregateOnly:false,ing:ing.diagnostics}}catch(e){return{...c,directSourceUrl:c.u,status:String(e.message).includes('blocked')?'blocked':'unavailable',reviews:[],reviewCount:0,publicCount:c.publicCount,aggregateOnly:false,error:text(e.message),ing:{providers:[],embedded:0,paginationPagesFetched:0,providerEndpointsFetched:0,blocked:String(e.message).includes('blocked')?1:0,failed:String(e.message).includes('blocked')?0:1}}}}
async function enrichCounts(req,title,desc,pages){const need=pages.filter(x=>x.publicCount==null).slice(0,12);if(!need.length)return{attempted:0,filled:0};try{const prompt=`Use public web search only to verify TOTAL review/rating counts for these already-verified exact product listings. Do not discover replacement listings and do not quote review text. Never invent counts. PRODUCT: ${title}\nFACTS: ${desc}\nLISTINGS: ${JSON.stringify(need.map((x,i)=>({id:i+1,url:x.directSourceUrl,asin:x.asin,title:x.title})))}\nReturn ONLY JSON {"sources":[{"id":1,"reviewCountEstimate":null,"ratingEstimate":null}]}.`,{p}=await ai(req,{input:prompt,tools:[{type:'web_search',search_context_size:'high'}],tool_choice:'required',include:['web_search_call.action.sources']},60000);let filled=0;for(const r of p.sources||[]){const x=need[Number(r.id)-1];if(!x)continue;const c=count(r.reviewCountEstimate);if(c!=null){x.publicCount=c;filled++}const rt=n(r.ratingEstimate);if(rt!=null&&rt<=5)x.rating=rt}return{attempted:need.length,filled}}catch(e){return{attempted:need.length,filled:0,error:text(e.message).slice(0,180)}}}
function refs(pages){const out=[];for(const p of pages)for(const r of p.reviews||[]){const body=text(r.body).slice(0,1400),k=body.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(body.length<10)continue;out.push({referenceId:`REF-${hash(`${p.directSourceUrl}|${r.reviewId||''}|${k}`)}`,platform:host(p.directSourceUrl),provider:(p.ing?.providers||[])[0]||null,sourceUrl:p.directSourceUrl,sourceRating:Number(r.rating)||null,sourceTitle:text(r.title).slice(0,180),sourceBody:body,sourceReviewId:text(r.reviewId),sourceVerifiedPurchase:Boolean(r.verifiedPurchase),sourceReviewDate:r.reviewDate||null,sourceAuthorName:text(r.authorName).slice(0,160),wordCount:body.split(/\s+/).length,sentenceCount:sent(body)})}return uniqueReferences(out,{limit:1200})}
function platformCounts(rs){const m=new Map();for(const r of rs){const k=`${r.platform}|${r.provider||''}`,x=m.get(k)||{platform:r.platform,provider:r.provider,reviewCount:0,pages:new Set()};x.reviewCount++;x.pages.add(r.sourceUrl);m.set(k,x)}return[...m.values()].map(x=>({platform:x.platform,provider:x.provider,reviewCount:x.reviewCount,pageCount:x.pages.size})).sort((a,b)=>b.reviewCount-a.reviewCount)}
function sourceCounts(pages){return pages.map(p=>({platform:host(p.directSourceUrl),provider:isAmazonUrl(p.directSourceUrl)?'bright_data_google_lens':((p.ing?.providers||[])[0]||'bright_data_google_lens'),sourceUrl:p.directSourceUrl,directSourceUrl:p.directSourceUrl,asin:p.asin||amazonAsin(p.directSourceUrl)||null,title:p.title||null,status:p.status,matchConfidence:Number((p.matchScore||p.score||0).toFixed(3)),confidence:p.confidence,publicReviewCount:p.publicCount??null,countKind:p.publicCount!=null?(p.status==='found'?'page_or_lens':'lens_or_web'):null,extractedReviewCount:p.reviewCount||0,individualExtractedCount:p.reviewCount||0,pageCount:1,aggregateOnly:Boolean(p.aggregateOnly),ratingEstimate:p.rating??null,error:p.error||null,linkVerified:true,linkVerification:p.method,lensTabs:p.tabs,lensRank:p.rank,verificationMethod:p.method,verificationReason:p.aiReason||null})).sort((a,b)=>((b.individualExtractedCount||0)-(a.individualExtractedCount||0))||((b.matchConfidence||0)-(a.matchConfidence||0))||String(a.platform).localeCompare(String(b.platform)))}

export async function POST(req){
  const started=Date.now();
  try{
    const key=process.env.BRIGHT_DATA_API_KEY||'';
    if(!key)throw Error('Bright Data Lens is not configured.');
    if(!gatewayToken(req))throw Error('AI Gateway verification is not configured.');
    const q=await req.json(),budget=referenceBudget(q.referenceBudget),productUrl=String(q.productUrl||'').trim(),productTitle=text(q.productTitle),productDescription=text(q.productDescription);
    if(!productUrl||!productTitle)throw Error('Product URL and title are required.');
    const source=await html(productUrl,20000),srcImages=images(source.h,source.u,budget.maxImages);
    if(!srcImages.length)throw Error('No public product images were found for Google Lens discovery.');
    const tabs=['exact_matches','products','visual_matches'],jobs=[];
    for(let i=0;i<srcImages.length;i++)for(const tab of tabs)jobs.push({i,tab,p:lens(tab,srcImages[i],key)});
    const settled=await Promise.allSettled(jobs.map(x=>x.p)),rows=[],diag={requests:jobs.length,succeeded:0,failed:0,tabs:{}};
    for(let i=0;i<settled.length;i++){
      const j=jobs[i],s=settled[i],k=`image${j.i+1}:${j.tab}`;
      if(s.status==='fulfilled'){
        const r=lensRows(j.tab,s.value,j.i);rows.push(...r);diag.succeeded++;diag.tabs[k]={ok:true,results:r.length,amazon:r.filter(x=>isAmazonUrl(x.u)).length};
      }else{diag.failed++;diag.tabs[k]={ok:false,error:text(s.reason?.message||s.reason).slice(0,180)}}
    }
    if(!diag.succeeded)throw Error('Google Lens discovery failed for every product image.');
    const candidates=dedupe(rows,host(source.u),budget.maxCandidates),verified=await verify(req,productTitle,productDescription,srcImages,candidates),acceptedAll=verified.filter(x=>x.accepted),accepted=selectDiverseCandidates(acceptedAll,{limit:budget.maxSources,maxPerHost:4}),pages=await Promise.all(accepted.map(x=>scrape(x,budget))),countDiagnostics=budget.useAiCountEnrichment?await enrichCounts(req,productTitle,productDescription,pages):{attempted:0,filled:0,skipped:true,reason:'test_budget'},referenceRecords=refs(pages),generationReferences=referenceRecords.slice(0,250),sources=sourceCounts(pages),aggregate=sources.filter(x=>x.aggregateOnly).map(x=>({platform:x.platform,provider:x.provider,sourceUrl:x.sourceUrl,directSourceUrl:x.directSourceUrl,asin:x.asin,sameProductConfidence:x.matchConfidence,reviewCountEstimate:x.publicReviewCount,ratingEstimate:x.ratingEstimate,lensTabs:x.lensTabs,verificationMethod:x.verificationMethod})),ing=pages.reduce((z,p)=>{const d=p.ing||{};z.embedded+=d.embedded||0;z.paginationPagesFetched+=d.paginationPagesFetched||0;z.providerEndpointsFetched+=d.providerEndpointsFetched||0;z.blocked+=d.blocked||0;z.failed+=d.failed||0;for(const x of d.providers||[])z.providers.add(x);if(p.status==='found')z.accessible++;if(p.status==='blocked')z.listingBlocked++;if(p.status==='unavailable')z.listingFailed++;return z},{embedded:0,paginationPagesFetched:0,providerEndpointsFetched:0,blocked:0,failed:0,providers:new Set(),accessible:0,listingBlocked:0,listingFailed:0}),confidence=sources.some(x=>x.confidence==='high')?'high':sources.some(x=>x.confidence==='medium')?'medium':sources.length?'low':'none';
    return Response.json({referenceSet:{version:'individual-reference-v13',provider:'bright_data_google_lens_first',discoveryModel:'bright_data_google_lens',verificationModel:MODEL,countModel:MODEL,amazonPriority:false,imageWebSearch:false,amazonResolutionStrategy:'lens_discovery_then_bounded_marketplace_enrichment',referenceBudget:budget,productUrl:source.u,productTitle,totalIndividualReviews:generationReferences.length,totalPulledReviews:referenceRecords.length,availableForGeneration:generationReferences.length,platformCounts:platformCounts(generationReferences),sourceCounts:sources,aggregateOnlySources:aggregate,references:generationReferences,pulledReferences:referenceRecords,confidence,matchedPages:sources.length,candidatePages:candidates.length,verifiedSourceLinks:sources.length,lensDiscovery:{enabled:true,provider:'bright_data_google_lens',zone:ZONE,status:'complete',budget,sourceImages:srcImages,rawResults:rows.length,uniqueCandidates:candidates.length,verifiedAcceptedCandidates:acceptedAll.length,acceptedCandidates:accepted.length,rejectedCandidates:verified.length-acceptedAll.length,amazonCandidates:candidates.filter(x=>isAmazonUrl(x.u)).length,amazonAccepted:accepted.filter(x=>isAmazonUrl(x.u)).length,...diag},verificationDiagnostics:{model:MODEL,candidates:candidates.length,accepted:acceptedAll.length,selected:accepted.length,rejected:verified.length-acceptedAll.length,exactAccepted:acceptedAll.filter(x=>x.tabs.includes('exact_matches')).length,productAccepted:acceptedAll.filter(x=>x.tabs.includes('products')).length,visualOnlyAccepted:acceptedAll.filter(x=>x.tabs.length===1&&x.tabs[0]==='visual_matches').length},countDiagnostics,ingestion:{embedded:ing.embedded,paginationPagesFetched:ing.paginationPagesFetched,providerEndpointsFetched:ing.providerEndpointsFetched,blocked:ing.blocked,failed:ing.failed,listingAccessible:ing.accessible,listingBlocked:ing.listingBlocked,listingFailed:ing.listingFailed,providers:[...ing.providers]},provenance:{discoveryOrder:['pdp_product_images','bright_data_google_lens','same_product_verification','diverse_verified_source_selection','verified_listing_review_ingestion','review_count_enrichment','reference_corpus'],imagesScanned:srcImages.length,heroImageUrl:srcImages[0],lensRequests:jobs.length,lensRequestsSucceeded:diag.succeeded,lensRawResults:rows.length,lensUniqueCandidates:candidates.length,verifiedCandidates:acceptedAll.length,selectedSources:accepted.length,reviewSources:sources.length,generatedAt:new Date().toISOString(),durationMs:Date.now()-started},syntheticUseOnly:true,sourceReviewTextExported:true}},{headers:{'cache-control':'no-store'}})
  }catch(e){return Response.json({error:e?.message||'External reference scan failed.'},{status:400,headers:{'cache-control':'no-store'}})}
}
