import { createHash, timingSafeEqual } from 'node:crypto';
export const runtime='nodejs';export const dynamic='force-dynamic';export const maxDuration=300;
const HASH='eeb803ca9122d1d9568f48ba0f36938c2907894d25f455d2a10edb7985b95e4f';
const EXPIRES=Date.parse('2026-09-12T12:00:00Z');
const BEARER='Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA';
const QUERY='HJ9lpOL-ZlOk5CkCw0JW6Q';
const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36';
const H={'cache-control':'private, no-store','x-robots-tag':'noindex'};
const hash=x=>createHash('sha256').update(String(x)).digest('hex');
const FEATURES={creator_subscriptions_tweet_preview_api_enabled:true,premium_content_api_read_enabled:false,communities_web_enable_tweet_community_results_fetch:true,c9s_tweet_anatomy_moderator_badge_enabled:true,responsive_web_grok_analyze_button_fetch_trends_enabled:false,responsive_web_grok_analyze_post_followups_enabled:true,responsive_web_jetfuel_frame:false,responsive_web_grok_share_attachment_enabled:true,responsive_web_grok_annotations_enabled:true,articles_preview_enabled:true,responsive_web_edit_tweet_api_enabled:true,graphql_is_translatable_rweb_tweet_is_translatable_enabled:true,view_counts_everywhere_api_enabled:true,longform_notetweets_consumption_enabled:true,responsive_web_twitter_article_tweet_consumption_enabled:true,tweet_awards_web_tipping_enabled:false,responsive_web_grok_show_grok_translated_post:false,responsive_web_grok_analysis_button_from_backend:true,post_ctas_fetch_enabled:false,creator_subscriptions_quote_tweet_preview_enabled:false,freedom_of_speech_not_reach_fetch_enabled:true,standardized_nudges_misinfo:true,tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled:true,longform_notetweets_rich_text_read_enabled:true,longform_notetweets_inline_media_enabled:true,profile_label_improvements_pcf_label_in_post_enabled:true,responsive_web_profile_redirect_enabled:true,rweb_tipjar_consumption_enabled:true,verified_phone_label_enabled:false,responsive_web_grok_image_annotation_enabled:true,responsive_web_grok_imagine_annotation_enabled:true,responsive_web_grok_community_note_auto_translation_is_enabled:true,responsive_web_graphql_skip_user_profile_image_extensions_enabled:false,responsive_web_graphql_timeline_navigation_enabled:true,responsive_web_enhance_cards_enabled:false};
const TOGGLES={withArticleRichContentState:true,withArticlePlainText:true,withGrokAnalyze:false,withDisallowedReplyControls:false,withPayments:true,withAuxiliaryUserLabels:true};
function articleFrom(x){const r=x?.data?.tweetResult?.result;const t=r?.tweet||r;return t?.article?.article_results?.result||t?.legacy?.article?.article_results?.result||null}
export async function GET(req){const q=new URL(req.url).searchParams,token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||q.get('ticket')||'',tweetId=q.get('tweet_id')||'';const ok=token&&Date.now()<EXPIRES&&timingSafeEqual(Buffer.from(hash(token),'hex'),Buffer.from(HASH,'hex'));if(!ok||!/^\d{8,24}$/.test(tweetId))return new Response('Not found',{status:404});try{const g=await fetch('https://api.x.com/1.1/guest/activate.json',{method:'POST',headers:{authorization:BEARER,'user-agent':UA},signal:AbortSignal.timeout(30000)});const gt=await g.json();if(!g.ok||!gt.guest_token)return Response.json({stage:'guest',status:g.status,body:gt},{status:502,headers:H});const u=new URL(`https://x.com/i/api/graphql/${QUERY}/TweetResultByRestId`);u.searchParams.set('variables',JSON.stringify({tweetId,withCommunity:false,includePromotedContent:false,withVoice:true}));u.searchParams.set('features',JSON.stringify(FEATURES));u.searchParams.set('fieldToggles',JSON.stringify(TOGGLES));const r=await fetch(u,{headers:{authorization:BEARER,'x-guest-token':gt.guest_token,'user-agent':UA,accept:'application/json','x-twitter-active-user':'yes','x-twitter-client-language':'en'},signal:AbortSignal.timeout(60000)});const tx=await r.text();let data;try{data=JSON.parse(tx)}catch{data={raw:tx.slice(0,2000)}};const a=articleFrom(data);return Response.json({status:r.status,topKeys:data&&typeof data==='object'?Object.keys(data):[],article:a?{keys:Object.keys(a),title:a.title,preview_text:a.preview_text,plain_text:a.plain_text,plain_len:(a.plain_text||'').length,blocks:a.content_state?.blocks?.length||0,media_entities:a.media_entities||null,cover_media:a.cover_media||null}:null,error:data?.errors||null,raw:r.ok?undefined:data},{status:r.ok?200:502,headers:H})}catch(e){return Response.json({error:String(e?.message||e).slice(0,1000)},{status:502,headers:H})}}
