import { createHash, timingSafeEqual } from 'node:crypto';
export const dynamic='force-dynamic';
export const maxDuration=120;
const TOKEN_HASH='864b6a8460312f068edfa85aedff69be9a0c48034e4e51e005289be9f22cee66';
const EXPIRES=Date.parse('2026-10-07T03:00:00Z');
const CITIES=['Dallas,Texas,United States','Houston,Texas,United States','San Antonio,Texas,United States','Tampa,Florida,United States','Jacksonville,Florida,United States','Charlotte,North Carolina,United States','Nashville,Tennessee,United States','Oklahoma City,Oklahoma,United States','Indianapolis,Indiana,United States','Columbus,Ohio,United States'];
function allowed(req){const token=(req.headers.get('authorization')||'').replace(/^Bearer /,'');return Date.now()<EXPIRES&&timingSafeEqual(createHash('sha256').update(token).digest(),Buffer.from(TOKEN_HASH,'hex'));}
async function bd(path,body){const key=process.env.BRIGHT_DATA_API_KEY;if(!key)throw Error('Bright Data not configured');const r=await fetch('https://api.brightdata.com'+path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+key,'content-type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(95000)});const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{data=raw.slice(0,2500000)}return {status:r.status,data};}
export async function GET(req){if(!allowed(req))return Response.json({error:'Unauthorized or expired'},{status:401});try{const r=await bd('/zone/get_all_zones');return Response.json({status:r.status,zones:Array.isArray(r.data)?r.data.map(x=>({name:x.name,type:x.type,plan:x.plan})):r.data},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error('Shopping geo zone inspection failed');return Response.json({error:e.message},{status:502});}}
export async function POST(req){if(!allowed(req))return Response.json({error:'Unauthorized or expired'},{status:401});try{const b=await req.json();if(!CITIES.includes(b.city)||!['desktop','mobile'].includes(b.device)||typeof b.zone!=='string'||!/^[a-zA-Z0-9_]+$/.test(b.zone))return Response.json({error:'Invalid input'},{status:400});const u=new URL('https://www.google.com/search');u.searchParams.set('q','30 ft flagpole');u.searchParams.set('gl','us');u.searchParams.set('hl','en');u.searchParams.set('uule',b.city);u.searchParams.set('brd_mobile',b.device==='mobile'?'android':'0');u.searchParams.set('brd_browser','chrome');u.searchParams.set('brd_json',b.html?'html':'1');if(b.shopping)u.searchParams.set('udm','28');const result=await bd('/request',{zone:b.zone,url:u.toString(),format:'raw',country:'us'});return Response.json({query:'30 ft flagpole',city:b.city,device:b.device,capturedAt:new Date().toISOString(),...result},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error('Shopping geo scan failed');return Response.json({error:e.message},{status:502});}}
