const UA='Mozilla/5.0 (compatible; SyntheticReviewLab/1.0; +internal QA review ingestion)';
const BLOCKED_HOST=/(^localhost$|\.local$|^0\.|^10\.|^127\.|^169\.254\.|^192\.168\.|^172\.(?:1[6-9]|2\d|3[01])\.|^\[?::1\]?$)/i;
const PROVIDERS={judgeme:/judge\.me$/i,yotpo:/yotpo\.com$/i,loox:/loox\.(?:io|app)$/i,stamped:/stamped\.io$/i};
function publicUrl(x,base){try{const u=new URL(String(x||'').replace(/&amp;/g,'&'),base);if(!/^https?:$/.test(u.protocol)||BLOCKED_HOST.test(u.hostname))return null;return u}catch{return null}}
function clean(s){return String(s||'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&#x([0-9a-f]+);/gi,(_,h)=>String.fromCodePoint(parseInt(h,16))).replace(/&#(\d+);/g,(_,d)=>String.fromCodePoint(Number(d))).replace(/\s+/g,' ').trim()}
function walk(x,fn,seen=new Set()){if(!x||typeof x!=='object'||seen.has(x))return;seen.add(x);fn(x);if(Array.isArray(x))for(const v of x)walk(v,fn,seen);else for(const v of Object.values(x))walk(v,fn,seen)}
function walkStrings(x,fn,seen=new Set()){if(x==null)return;if(typeof x==='string'){fn(x);return}if(typeof x!=='object'||seen.has(x))return;seen.add(x);if(Array.isArray(x))for(const v of x)walkStrings(v,fn,seen);else for(const v of Object.values(x))walkStrings(v,fn,seen)}
function providerFor(url){const h=publicUrl(url)?.hostname.replace(/^www\./,'')||'';for(const [k,re] of Object.entries(PROVIDERS))if(re.test(h))return k;return null}
function looksReviewish(o){if(!o||typeof o!=='object')return false;const t=o['@type'];if(t==='Review'||(Array.isArray(t)&&t.includes('Review'))||o.reviewBody)return true;const hasBody=typeof(o.content||o.body||o.text||o.message)==='string';if(!hasBody)return false;const hasRating=o.score!=null||o.rating!=null||o.ratingValue!=null||o.stars!=null||Boolean(o.reviewRating);const hasReviewer=Boolean(o.reviewer||o.reviewer_name||o.reviewerName||o.author?.name||o.user?.name);const hasReviewId=o.review_id!=null||o.reviewId!=null;const hasBuyer=o.verified_buyer!=null||o.verifiedBuyer!=null;return Boolean((hasRating&&(hasReviewer||hasReviewId||hasBuyer))||(hasReviewer&&hasReviewId)||(hasReviewId&&hasBuyer))}
function normalizeReview(o){if(!looksReviewish(o))return null;const t=o?.['@type'];const typed=t==='Review'||(Array.isArray(t)&&t.includes('Review'))||Boolean(o.reviewBody);const body=clean(o.reviewBody||(typed?o.description:'')||o.content||o.body||o.text||o.message||'');if(body.length<10||body.length>3000)return null;let rating=o?.reviewRating?.ratingValue??o?.ratingValue??o?.score??o?.rating??o?.stars;rating=Number(String(rating??'').match(/[0-9.]+/)?.[0]);if(!(rating>=1&&rating<=5))rating=null;const title=clean(o.title||o.name||o.headline||o.summary||'').slice(0,220),reviewId=clean(o.review_id||o.reviewId||o.id||o.uuid||''),verifiedPurchase=Boolean(o.verified_purchase??o.verifiedPurchase??o.verified_buyer??o.verifiedBuyer??o.is_verified),reviewDate=o.datePublished||o.review_date||o.reviewDate||o.created_at||o.createdAt||o.date||null,author=o.author?.name||o.author||o.reviewer?.name||o.reviewer||o.reviewer_name||o.reviewerName||o.user?.name||'';return{rating,title,body,reviewId,verifiedPurchase,reviewDate,authorName:clean(author).slice(0,160)}}
function dedupe(xs,max=800){const seen=new Set(),out=[];for(const r of xs){if(!r?.body)continue;const k=r.body.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(k.length<8||seen.has(k))continue;seen.add(k);out.push(r);if(out.length>=max)break}return out}
function jsonScripts(html){const out=[];for(const m of String(html||'').matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)){const type=m[0].match(/type=["']([^"']+)/i)?.[1]||'',s=m[1].trim();if(!s||s.length>2500000)continue;if(!/json/i.test(type)&&!/^[\[{]/.test(s))continue;try{out.push(JSON.parse(s))}catch{}}return out}
function lastClassText(before,className){const re=new RegExp(`<[^>]*class=["'][^"']*\\b${className.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b[^"']*["'][^>]*>([\\s\\S]*?)<\\/[^>]+>`,'gi');let hit=null;for(const m of String(before||'').matchAll(re))hit=m[1];return hit==null?'':clean(hit)}
function lastAttr(before,className,attr){const re=new RegExp(`<[^>]*class=["'][^"']*\\b${className.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b[^"']*["'][^>]*\\b${attr}=["']([^"']+)["'][^>]*>`,'gi');let hit=null;for(const m of String(before||'').matchAll(re))hit=m[1];return hit}
function judgeMeHtmlReviews(raw){let html=String(raw||'');if(!/jdgm-rev__body/i.test(html))return[];html=html.replace(/\\u003c/gi,'<').replace(/\\u003e/gi,'>').replace(/\\u0026/gi,'&').replace(/\\\//g,'/').replace(/\\"/g,'"').replace(/\\'/g,"'");const out=[],re=/<(?:div|p)[^>]*class=["'][^"']*\bjdgm-rev__body\b[^"']*["'][^>]*>([\s\S]*?)<\/(?:div|p)>/gi;for(const m of html.matchAll(re)){const body=clean(m[1]);if(body.length<10||body.length>3000)continue;const before=html.slice(Math.max(0,(m.index||0)-5000),m.index||0),title=lastClassText(before,'jdgm-rev__title').slice(0,220),ratingRaw=lastAttr(before,'jdgm-rev__rating','data-score');let rating=Number(ratingRaw);if(!(rating>=1&&rating<=5))rating=null;out.push({rating,title,body})}return dedupe(out)}
export function extractReviews(payload){const text=String(payload||''),out=[...judgeMeHtmlReviews(text)];try{const j=JSON.parse(text);walk(j,o=>{const r=normalizeReview(o);if(r)out.push(r)});walkStrings(j,s=>{if(/jdgm-rev__body/i.test(s))out.push(...judgeMeHtmlReviews(s))})}catch{}for(const j of jsonScripts(text)){walk(j,o=>{const r=normalizeReview(o);if(r)out.push(r)});walkStrings(j,s=>{if(/jdgm-rev__body/i.test(s))out.push(...judgeMeHtmlReviews(s))})}for(const m of text.matchAll(/["']reviewBody["']\s*:\s*["']((?:\\.|[^"']){10,2500})["']/gi)){try{const body=JSON.parse('"'+m[1].replace(/"/g,'\\"')+'"'),r=normalizeReview({reviewBody:body});if(r)out.push(r)}catch{}}return dedupe(out)}
function reviewLinks(html,base){const baseUrl=publicUrl(base);if(!baseUrl)return[];const out=new Map(),add=(raw,why)=>{const u=publicUrl(raw,base);if(!u)return;u.hash='';if(/\.(?:js|css|png|jpe?g|gif|svg|webp|woff2?|ico)(?:\?|$)/i.test(u.href))return;const same=u.hostname===baseUrl.hostname,provider=providerFor(u.href),reviewish=/(?:review|rating|widget|product_review|filter\.json)/i.test(u.pathname+u.search);if(!reviewish)return;if(!same&&!provider)return;const key=u.href;if(!out.has(key))out.set(key,{url:key,provider:provider||'same_host',why})};for(const m of String(html||'').matchAll(/(?:href|src|data-url|data-src|data-endpoint|data-api-url)\s*=\s*["']([^"']+)["']/gi))add(m[1],'markup');for(const m of String(html||'').matchAll(/https?:\\?\/\\?\/[^\s"'<>]+/gi))add(m[0].replace(/\\\//g,'/'),'embedded_url');return[...out.values()]}
function sameHostPages(html,base){const b=publicUrl(base);if(!b)return[];const out=[];for(const m of String(html||'').matchAll(/href\s*=\s*["']([^"']+)["']/gi)){const u=publicUrl(m[1],base);if(!u||u.hostname!==b.hostname)continue;const s=(u.pathname+u.search+u.hash).toLowerCase();if(!/review/.test(s)||!/(?:page|p=|offset|cursor|reviews?\/)/.test(s))continue;u.hash='';if(!out.includes(u.href))out.push(u.href)}return out}
function judgeMeInferred(html){if(!/judge\.me|jdgm-/i.test(html))return[];const shop=String(html).match(/(?:shop_domain|shopDomain|myshopify_domain)\s*[:=]\s*["']([^"']+\.myshopify\.com)["']/i)?.[1]||String(html).match(/([a-z0-9][a-z0-9-]*\.myshopify\.com)/i)?.[1];const token=String(html).match(/(?:judgeme[_-]?(?:public[_-]?)?(?:api[_-]?)?token|public[_-]?api[_-]?token|api_token)\s*[:=]\s*["']([^"']{8,})["']/i)?.[1];const external=String(html).match(/(?:product[_-]?id|productId|external_id|externalId)\s*[:=]\s*["']?(\d{5,})/i)?.[1];if(!shop||!token||!external)return[];const out=[];for(let page=1;page<=4;page++){const u=new URL('https://judge.me/api/v1/widgets/product_review');u.searchParams.set('shop_domain',shop);u.searchParams.set('api_token',token);u.searchParams.set('external_id',external);u.searchParams.set('page',String(page));u.searchParams.set('per_page','100');u.searchParams.set('json_request','true');out.push({url:u.href,provider:'judgeme',why:'public_widget_api'})}return out}
async function fetchPublic(url,timeout=12000){const u=publicUrl(url);if(!u)throw Error('unsafe_url');const r=await fetch(u,{headers:{'user-agent':UA,'accept':'application/json,text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(timeout)});const text=await r.text();if(r.status===403||r.status===429||/captcha|robot check|verify you are human|access denied/i.test(text.slice(0,5000)))throw Error('blocked_or_challenged');if(!r.ok)throw Error(`http_${r.status}`);return{text,url:r.url,contentType:r.headers.get('content-type')||''}}
export async function ingestReviewsFromPage({html,url,maxPages=5,maxEndpoints=10}){const baseReviews=extractReviews(html),providers=new Set(),diagnostics={embedded:baseReviews.length,paginationPagesFetched:0,providerEndpointsFetched:0,blocked:0,failed:0,providers:[]},collected=[...baseReviews];for(const k of ['judgeme','yotpo','loox','stamped'])if(new RegExp(k==='judgeme'?'judge\\.me|jdgm-':k,'i').test(html))providers.add(k);const endpoints=[...judgeMeInferred(html),...reviewLinks(html,url)].slice(0,maxEndpoints);for(const e of endpoints){try{const p=await fetchPublic(e.url),rs=extractReviews(p.text);collected.push(...rs);diagnostics.providerEndpointsFetched++;if(e.provider)providers.add(e.provider)}catch(err){if(String(err.message).includes('blocked'))diagnostics.blocked++;else diagnostics.failed++}}
const pages=sameHostPages(html,url).slice(0,Math.max(0,maxPages-1));for(const purl of pages){try{const p=await fetchPublic(purl),rs=extractReviews(p.text);collected.push(...rs);diagnostics.paginationPagesFetched++}catch(err){if(String(err.message).includes('blocked'))diagnostics.blocked++;else diagnostics.failed++}}
diagnostics.providers=[...providers];const reviews=dedupe(collected,800);return{reviews,diagnostics}}
export function isAmazonUrl(url){const h=publicUrl(url)?.hostname.replace(/^www\./,'')||'';return /(^|\.)amazon\.(?:com|ca|com\.mx|com\.br|co\.uk|de|fr|it|es|in|co\.jp|com\.au|ae|com\.tr|sg|nl|se|pl|be|ie|eg|sa)$/i.test(h)}
export function amazonAsin(url){const s=String(url||'');return s.match(/\/(?:dp|gp\/product|product-reviews)\/([A-Z0-9]{10})(?:[/?]|$)/i)?.[1]?.toUpperCase()||null}
