import{createHash,timingSafeEqual}from'node:crypto';
export const runtime='nodejs';export const dynamic='force-dynamic';export const maxDuration=300;
const HASH='5092bf572197b3984dce0d2750cbeb059f88e517d22da0b9c668d8374facbcc6';
const EXPIRES=Date.parse('2026-09-12T00:00:00Z');
const STORE='https://plcqypajqvtpnjctdlho.supabase.co/functions/v1/nate-archive-store';
const PROFILE='https://site.twstalker.com/Nate_Google_',TARGET='https://site.twstalker.com/service/api',ZONE='synthetic_review_ebay_items';
const PROFILE_ID='1544391592106201091',SEED='nate_425865145ed94ddb1861b037500e29cf';
const SOURCE_JOB='nate-archive-407e3e82e69f4e56144efddf66d6b35f';
const H={'cache-control':'private, no-store','referrer-policy':'no-referrer','x-robots-tag':'noindex'};
const hash=x=>createHash('sha256').update(String(x)).digest('hex');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function authorized(req){const p=new URL(req.url).searchParams,t=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||p.get('ticket')||'';return Boolean(t)&&Date.now()<EXPIRES&&timingSafeEqual(Buffer.from(hash(t),'hex'),Buffer.from(HASH,'hex'))}
function cleanText(v){return String(v||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').replace(/\n\s+/g,'\n').trim()}
function postId(v){const s=String(v??'');return /^\d{8,24}$/.test(s)?s:null}
function articleUrls(v){return[...new Set((JSON.stringify(v).match(/https?:\/\/(?:www\.)?(?:x|twitter)\.com\/(?:i\/article|[^/\s"\\]+\/article)\/\d+/gi)||[]))]}
function rowsFromBody(body,page){const entries=body&&typeof body==='object'&&body.tweets&&typeof body.tweets==='object'?Object.entries(body.tweets):[];const rows=[];for(const[idKey,t]of entries){const id=postId(idKey)||postId(t?.id_str)||postId(t?.id);if(!id)continue;const author=String(t?.core?.screen_name||'').replace(/^@/,'');if(author.toLowerCase()!=='nate_google_')continue;const d=t?.created_at,iso=d&&Number.isFinite(Date.parse(d))?new Date(d).toISOString():null;const conv=postId(t?.conversation_id_str)||postId(t?.conversation_id);const kind=t?.is_retweet?'repost':conv&&conv!==id?'reply':t?.is_quote_status?'quote_post':'post';rows.push({id,source_job:SOURCE_JOB,author_handle:'Nate_Google_',is_authored_by_target:true,content_kind:kind,text:cleanText(t?.full_text||t?.text||''),url:'https://x.com/Nate_Google_/status/'+id,published_at:iso,parent_post_id:null,conversation_id:conv,article_urls:articleUrls(t),raw:{...t,id_str:id,mirror_page:page,mirror_source:'twstalker_via_bright_data'}})}return rows}
export async function GET(req){
 if(!authorized(req))return new Response('Not found',{status:404});
 const p=new URL(req.url).searchParams,token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||p.get('ticket')||'';const key=process.env.BRIGHT_DATA_API_KEY||'';
 const safe=e=>String(e?.message||e).split(key).join('[REDACTED]').slice(0,1600);
 async function store(op,b={}){const r=await fetch(STORE,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({op,...b}),cache:'no-store',signal:AbortSignal.timeout(45000)}),t=await r.text();let v;try{v=t?JSON.parse(t):null}catch{throw Error('Storage invalid response')};if(!r.ok)throw Error('Storage '+r.status+': '+JSON.stringify(v).slice(0,700));return v}
 async function upstream(path,body){const r=await fetch('https://api.brightdata.com'+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer '+key,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),cache:'no-store',signal:AbortSignal.timeout(95000)}),text=await r.text();let value;try{value=JSON.parse(text)}catch{value=text}return{status:r.status,value}}
 async function saveRows(rows){for(let i=0;i<rows.length;i+=100)await store('save_posts',{rows:rows.slice(i,i+100)});return rows.length}
 async function ingestComplete(job){if(job?.diagnostics?.ingested_at)return{saved:Number(job.diagnostics.ingested_count||0),already:true};const full=await store('get',{id:job.id});const body=full?.raw_records?.[0]?.response;const rows=rowsFromBody(body,job.request.page);const saved=await saveRows(rows);await store('patch',{id:job.id,patch:{diagnostics:{...(full.diagnostics||{}),ingested_at:new Date().toISOString(),ingested_count:saved}}});return{saved,already:false}}
 async function reconcile(limit=50){const jobs=(await store('list')).filter(j=>j.request?.mode==='mirror_cursor'&&j.status==='complete'&&!j.diagnostics?.ingested_at).sort((a,b)=>a.request.page-b.request.page).slice(0,limit);let saved=0;const pages=[];for(const j of jobs){const r=await ingestComplete(j);saved+=r.saved;pages.push({page:j.request.page,saved:r.saved})}return{pages,saved,remaining:(await store('list')).filter(j=>j.request?.mode==='mirror_cursor'&&j.status==='complete'&&!j.diagnostics?.ingested_at).length}}
 async function poll(job){const result=await upstream('/unblocker/get_result?response_id='+encodeURIComponent(job.diagnostics.response_id));if(result.status===202)return{id:job.id,page:job.request.page,status:'running'};let body=result.value?.body??result.value;if(typeof body==='string'){try{body=JSON.parse(body)}catch{}}const http=result.value?.status_code??result.status;const entries=body&&typeof body==='object'&&body.tweets&&typeof body.tweets==='object'?Object.entries(body.tweets):[];if(http!==200||!body||typeof body!=='object'||!('tweets'in body)||!entries.length){const preview=JSON.stringify(body).slice(0,1200);await store('patch',{id:job.id,patch:{status:'failed',record_count:1,error:{message:'Invalid pagination response',http,preview},diagnostics:{...(job.diagnostics||{}),http,responsePreview:preview}}});return{id:job.id,page:job.request.page,status:'failed',http,preview}}
  const ids=entries.map(([id])=>id).filter(x=>/^\d{8,24}$/.test(x));const authored=entries.filter(([,t])=>String(t?.core?.screen_name||'').toLowerCase()==='nate_google_');const dates=authored.map(([,t])=>Date.parse(t?.created_at)).filter(Number.isFinite).sort((a,b)=>a-b);const cursor=typeof body.cursor==='string'?body.cursor:null,hasMore=Boolean(cursor&&cursor!==job.request.cursor&&entries.length);const diagnostics={...(job.diagnostics||{}),http,page:job.request.page,postCount:entries.length,authored:authored.length,postIds:ids,cursor,hasMore,oldest:dates.length?new Date(dates[0]).toISOString():null,newest:dates.length?new Date(dates.at(-1)).toISOString():null,responsePreview:null};await store('patch',{id:job.id,patch:{status:'complete',record_count:1,raw_records:[{response:body,transport:'bright_data_web_unlocker',url:TARGET}],diagnostics}});const completed={...job,status:'complete',diagnostics};const ing=await ingestComplete(completed);return{id:job.id,page:job.request.page,status:'complete',postCount:entries.length,authored:authored.length,saved:ing.saved,oldest:diagnostics.oldest,newest:diagnostics.newest,hasMore}}
 async function start(page,cursor){if(!cursor||page<2||page>400)throw Error('Invalid cursor/page');const config={mode:'mirror_cursor',url:TARGET,page,cursor,profile_id:PROFILE_ID};const id='nate_'+hash(JSON.stringify(config)).slice(0,32);const reserved=await store('reserve',{id,request:config,max:1});if(!reserved.created)return{...reserved.job,request:undefined,diagnostics:reserved.job?.diagnostics?{page:reserved.job.diagnostics.page,response_id:reserved.job.diagnostics.response_id}:undefined};const form=new URLSearchParams({page:String(page),cursor,data:PROFILE_ID,action:'profile'}).toString();const body={url:TARGET,method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8',Referer:PROFILE,Origin:'https://site.twstalker.com','X-Requested-With':'XMLHttpRequest'},body:form};const result=await upstream('/unblocker/req?zone='+ZONE,body);if(result.status!==200||!result.value?.response_id){await store('patch',{id,patch:{status:'trigger_unknown',error:{message:'Submit failed '+JSON.stringify(result).slice(0,900)}}});throw Error('Pagination submit failed')};await store('patch',{id,patch:{status:'mirror_running',diagnostics:{page,response_id:result.value.response_id}}});return{id,page,status:'running'} }
 async function step(){const jobs=(await store('list')).filter(j=>j.request?.mode==='mirror_cursor');const pending=jobs.find(j=>j.status==='mirror_running');if(pending)return poll(pending);if(jobs.some(j=>['reserved','trigger_unknown'].includes(j.status)))return{status:'blocked',message:'Ambiguous page requires reconciliation'};const complete=jobs.filter(j=>j.status==='complete').sort((a,b)=>b.request.page-a.request.page);let cursor,page=2;if(complete.length){const last=complete[0];if(!last.diagnostics?.hasMore)return{status:'timeline_exhausted',page:last.request.page,oldest:last.diagnostics?.oldest};cursor=last.diagnostics.cursor;page=last.request.page+1}else{const seed=await store('get',{id:SEED}),html=seed?.raw_records?.[0]?.html||'',tag=html.match(/<a\b[^>]*class=["'][^"']*add-nw-event[^"']*["'][^>]*>/i)?.[0]||'';cursor=tag.match(/data-cursor=["']([^"']+)["']/i)?.[1];page=Number(tag.match(/data-ec=["'](\d+)["']/i)?.[1]||2);if(tag.match(/data-query=["']([^"']+)["']/i)?.[1]!==PROFILE_ID)throw Error('Unexpected seed profile')};return start(page,cursor)}
 try{
  const op=p.get('op')||'status';
  if(op==='reconcile')return Response.json(await reconcile(100),{headers:H});
  if(op==='advance')return Response.json(await step(),{headers:H});
  if(op==='run'){const began=Date.now(),results=[],maxPages=Math.max(1,Math.min(Number(p.get('pages')||8),20));let completed=0;await reconcile(100);while(Date.now()-began<240000&&completed<maxPages){const s=await step();results.push(s);if(s.status==='complete')completed++;if(['timeline_exhausted','blocked','failed'].includes(s.status))break;await sleep(s.status==='running'?2500:250)}return Response.json({completed,results},{headers:H})}
  const jobs=(await store('list')).filter(j=>j.request?.mode==='mirror_cursor').sort((a,b)=>(a.request?.page||0)-(b.request?.page||0));return Response.json({sourceJob:SOURCE_JOB,pages:jobs.map(j=>({page:j.request.page,status:j.status,posts:j.diagnostics?.postCount,authored:j.diagnostics?.authored,ingested:j.diagnostics?.ingested_count,oldest:j.diagnostics?.oldest,newest:j.diagnostics?.newest,hasMore:j.diagnostics?.hasMore,error:j.error})),latestPage:jobs.at(-1)?.request?.page||1},{headers:H})
 }catch(e){return Response.json({error:safe(e)},{status:502,headers:H})}
}
export async function POST(req){return GET(req)}
