export const runtime='nodejs';
export const maxDuration=300;

import{ingestMarketplaceSource}from'../../../lib/marketplace-review-ingest';
import{collectAmazonReviewsV2,isAmazonV2}from'../../../lib/amazon-review-ingest-v2';
import{discoverAmazonVolumeCandidates}from'../../../lib/amazon-volume-discovery-v2';

function clean(x){return String(x||'').replace(/\s+/g,' ').trim()}
function host(x){try{return new URL(x).hostname.replace(/^www\./,'').toLowerCase()}catch{return''}}
function hash(s){let h=2166136261;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36).toUpperCase()}
function sent(s){return Math.max(1,(String(s).match(/[.!?]+(?:\s|$)/g)||[]).length)}
function recomputePlatformCounts(refs){const m=new Map();for(const r of refs||[]){const k=`${r.platform}|${r.provider||''}`,x=m.get(k)||{platform:r.platform,provider:r.provider,reviewCount:0,pages:new Set()};x.reviewCount++;x.pages.add(r.sourceUrl);m.set(k,x)}return[...m.values()].map(x=>({platform:x.platform,provider:x.provider,reviewCount:x.reviewCount,pageCount:x.pages.size})).sort((a,b)=>b.reviewCount-a.reviewCount)}
function marketplaceSources(rs){const map=new Map();for(const x of[...(rs?.sourceCounts||[]),...(rs?.aggregateOnlySources||[])]){const u=x?.directSourceUrl||x?.sourceUrl||'',h=host(u);if(!u||(!/(^|\.)amazon\./i.test(h)&&!/(^|\.)ebay\./i.test(h)))continue;if(!map.has(u))map.set(u,x)}return[...map.values()]}
function augmentWithDiscoveredAmazon(rs,discovery){if(!discovery?.candidates?.length)return rs;const sourceCounts=[...(rs.sourceCounts||[])],aggregateOnly=[...(rs.aggregateOnlySources||[])],seen=new Set([...sourceCounts,...aggregateOnly].map(x=>x.directSourceUrl||x.sourceUrl));for(const c of discovery.candidates){if(seen.has(c.url))continue;seen.add(c.url);sourceCounts.push({directSourceUrl:c.url,sourceUrl:c.url,platform:'amazon.com',provider:'bright_data_amazon_search',asin:c.asin,title:c.title||'Amazon',publicReviewCount:c.ratingCount??null,ratingEstimate:c.rating??null,individualExtractedCount:0,aggregateOnly:true,status:'found',matchConfidence:c.verificationConfidence,verificationMethod:'amazon_search+ai_visual',verificationReason:c.verificationReason||'',linkVerified:true,lensTabs:['amazon_search'],lensRank:null,discoveryOrigin:'amazon_high_volume'})}return{...rs,sourceCounts,aggregateOnlySources:aggregateOnly,amazonVolumeDiscovery:{queries:discovery.queries||[],diagnostics:discovery.diagnostics||{},candidates:discovery.candidates.map(c=>({asin:c.asin,url:c.url,title:c.title,ratingCount:c.ratingCount,verificationConfidence:c.verificationConfidence,verificationReason:c.verificationReason}))}}}
function selectSources(rs){const all=marketplaceSources(rs),hi=all.filter(x=>x.discoveryOrigin==='amazon_high_volume').sort((a,b)=>(Number(b.publicReviewCount)||0)-(Number(a.publicReviewCount)||0)),ebay=all.filter(x=>/(^|\.)ebay\./i.test(host(x.directSourceUrl||x.sourceUrl))).sort((a,b)=>(Number(b.publicReviewCount)||0)-(Number(a.publicReviewCount)||0)),amazon=all.filter(x=>isAmazonV2(x.directSourceUrl||x.sourceUrl)&&x.discoveryOrigin!=='amazon_high_volume').sort((a,b)=>(Number(b.publicReviewCount)||0)-(Number(a.publicReviewCount)||0));if(hi.length)return[hi[0],...ebay.slice(0,2)];return[...amazon.slice(0,4),...ebay.slice(0,3)].slice(0,7)}

export async function POST(req){
  let body;try{body=await req.json()}catch{return Response.json({error:'Invalid JSON body.'},{status:400})}
  let rs=body?.referenceSet;if(!rs||!Array.isArray(rs.references))return Response.json({error:'referenceSet is required.'},{status:400});
  let discovery={candidates:[],queries:[],diagnostics:{skipped:false}};try{discovery=await discoverAmazonVolumeCandidates(req,rs)}catch(e){discovery={candidates:[],queries:[],diagnostics:{error:clean(e?.message||e)}}}
  rs=augmentWithDiscoveredAmazon(rs,discovery);
  const sources=selectSources(rs);if(!sources.length)return Response.json({referenceSet:{...rs,marketplaceIngestion:{attemptedSources:0,appendedReviews:0,sources:[],amazonVolumeDiscovery:discovery.diagnostics||null}}},{headers:{'cache-control':'no-store'}});
  const existing=new Set((rs.references||[]).map(r=>clean(r.sourceBody).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()).filter(Boolean));
  const remaining=Math.max(1,250-(rs.references||[]).length),hasHighVolume=sources.some(x=>x.discoveryOrigin==='amazon_high_volume');
  const diagnostics=[],appended=[];
  const results=await Promise.all(sources.map(async src=>{try{const u=src?.directSourceUrl||src?.sourceUrl||'',isAmazon=isAmazonV2(u),isHigh=src.discoveryOrigin==='amazon_high_volume';let budget=remaining;if(hasHighVolume){if(isHigh)budget=Math.min(220,remaining);else if(/(^|\.)ebay\./i.test(host(u)))budget=Math.min(30,remaining);else budget=Math.min(20,remaining)}else if(isAmazon)budget=Math.min(80,remaining);else budget=Math.min(40,remaining);const result=isAmazon?await collectAmazonReviewsV2(src,{maxReviews:budget,maxBatches:1}):await ingestMarketplaceSource(src,{maxPages:3,maxReviews:budget});return{src,result,budget}}catch(e){return{src,budget:0,result:{reviews:[],provider:null,attempted:0,blocked:0,failed:1,error:clean(e?.message||e)}}}}));
  const sourceCounts=[...(rs.sourceCounts||[])],aggregateOnly=[...(rs.aggregateOnlySources||[])];
  for(const {src,result,budget} of results){
    const sourceUrl=src.directSourceUrl||src.sourceUrl||'',platform=host(sourceUrl)||src.platform||'',provider=result.provider||src.provider||'marketplace';let added=0;
    for(const r of result.reviews||[]){const bodyText=clean(r.body),k=bodyText.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(!k||existing.has(k)||appended.length>=remaining)continue;existing.add(k);appended.push({referenceId:`REF-${hash(`${sourceUrl}|${bodyText}`).slice(0,8)}`,platform,provider,sourceUrl,sourceRating:r.rating??null,sourceTitle:clean(r.title).slice(0,220),sourceBody:bodyText,sourceReviewId:r.reviewId||'',sourceVerifiedPurchase:Boolean(r.verifiedPurchase),sourceReviewDate:r.reviewDate||null,wordCount:bodyText.split(/\s+/).filter(Boolean).length,sentenceCount:sent(bodyText)});added++}
    let row=sourceCounts.find(x=>(x.directSourceUrl||x.sourceUrl)===sourceUrl);if(added&&!row){row={...src,directSourceUrl:sourceUrl,sourceUrl:src.sourceUrl||sourceUrl,aggregateOnly:false,status:'found'};sourceCounts.push(row)}
    if(row&&added){row.individualExtractedCount=(Number(row.individualExtractedCount)||Number(row.extractedReviewCount)||Number(row.reviewCount)||0)+added;row.extractedReviewCount=row.individualExtractedCount;row.reviewCount=row.individualExtractedCount;row.aggregateOnly=false;row.provider=provider;row.status='found';if(result.aggregateRatingCount!=null)row.publicReviewCount=result.aggregateRatingCount;if(result.aggregateRating!=null)row.ratingEstimate=result.aggregateRating}
    diagnostics.push({sourceUrl,platform,provider,budget,discoveryOrigin:src.discoveryOrigin||null,attempted:result.attempted||0,blocked:result.blocked||0,failed:result.failed||0,pending:Boolean(result.pending),snapshotId:result.snapshotId||result.batches?.[0]?.snapshotId||null,canonicalUrl:result.canonicalUrl||null,requested:result.requested??null,aggregateRatingCount:result.aggregateRatingCount??null,rawRows:result.rawRows??null,parsedBodies:result.parsedBodies??null,reviewIdCount:result.reviewIdCount??null,extracted:added,error:result.error||''});
  }
  const references=[...(rs.references||[]),...appended].slice(0,250),active=new Set(references.map(r=>r.sourceUrl));
  const out={...rs,references,sourceCounts,aggregateOnlySources:aggregateOnly.filter(x=>!active.has(x.directSourceUrl||x.sourceUrl)),platformCounts:recomputePlatformCounts(references),totalIndividualReviews:references.length,availableForGeneration:Math.min(250,references.length),matchedPages:sourceCounts.length,verifiedSourceLinks:sourceCounts.filter(x=>x.linkVerified).length,marketplaceIngestion:{attemptedSources:sources.length,appendedReviews:appended.length,sources:diagnostics,amazonVolumeDiscovery:discovery.diagnostics||null}};
  return Response.json({referenceSet:out},{headers:{'cache-control':'no-store'}})
}
