export const runtime='nodejs';
export const maxDuration=300;

import{ingestMarketplaceSource}from'../../../lib/marketplace-review-ingest';
import{collectAmazonReviewsV2,isAmazonV2,amazonAsinV2}from'../../../lib/amazon-review-ingest-v2';
import{discoverAmazonVolumeCandidates}from'../../../lib/amazon-volume-discovery-v2';
import{getBrightDataBalance,classifyBrightDataFailure}from'../../../lib/bright-data-status';
import{interleaveReferencesBySource,isUsableReviewSource,sortBestReviewSources,sourceReviewVolume}from'../../../lib/reference-pipeline.mjs';

const MAX_GENERATION_REFS=250;
const MAX_EXPORT_REFS=1200;
const MAX_MARKETPLACE_PULLS=50;
const MIN_AMAZON_PER_SOURCE=5;

function clean(x){return String(x||'').replace(/\s+/g,' ').trim()}
function host(x){try{return new URL(x).hostname.replace(/^www\./,'').toLowerCase()}catch{return''}}
function hash(s){let h=2166136261;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36).toUpperCase()}
function sent(s){return Math.max(1,(String(s).match(/[.!?]+(?:\s|$)/g)||[]).length)}
function bodyKey(s){return clean(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function sourceKey(s){const u=clean(s?.directSourceUrl||s?.sourceUrl||'');const asin=clean(s?.asin||amazonAsinV2(u)||'').toUpperCase();return asin?`amazon:${asin}`:u.toLowerCase()}
function verifiedSource(s){const c=Number(s?.matchConfidence??s?.sameProductConfidence);return s?.linkVerified!==false&&(s?.verificationMethod||s?.linkVerification||s?.discoveryOrigin||Number.isFinite(c))&&(!Number.isFinite(c)||c>=.72)}
function recomputePlatformCounts(refs){const m=new Map();for(const r of refs||[]){const k=`${r.platform}|${r.provider||''}`,x=m.get(k)||{platform:r.platform,provider:r.provider,reviewCount:0,pages:new Set()};x.reviewCount++;x.pages.add(r.sourceUrl);m.set(k,x)}return[...m.values()].map(x=>({platform:x.platform,provider:x.provider,reviewCount:x.reviewCount,pageCount:x.pages.size})).sort((a,b)=>b.reviewCount-a.reviewCount)}
function existingSourceCounts(refs){const m=new Map();for(const r of refs||[]){const u=clean(r?.sourceUrl||'');if(!u)continue;const k=sourceKey({sourceUrl:u,asin:r?.sourceAsin});m.set(k,(m.get(k)||0)+1);m.set(u.toLowerCase(),(m.get(u.toLowerCase())||0)+1)}return m}
function marketplaceSources(rs){const map=new Map();for(const x of[...(rs?.sourceCounts||[]),...(rs?.aggregateOnlySources||[])]){const u=x?.directSourceUrl||x?.sourceUrl||'',h=host(u);if(!u||(!/(^|\.)amazon\./i.test(h)&&!/(^|\.)ebay\./i.test(h)))continue;const k=/(^|\.)amazon\./i.test(h)?sourceKey(x):u.toLowerCase();const old=map.get(k);if(!old||Number(x.matchConfidence||0)>Number(old.matchConfidence||0))map.set(k,x)}return[...map.values()]}
function augmentWithDiscoveredAmazon(rs,discovery){if(!discovery?.candidates?.length)return rs;const sourceCounts=[...(rs.sourceCounts||[])],aggregateOnly=[...(rs.aggregateOnlySources||[])],seen=new Set([...sourceCounts,...aggregateOnly].map(sourceKey));for(const c of discovery.candidates){const k=`amazon:${String(c.asin||'').toUpperCase()}`;if(seen.has(k))continue;seen.add(k);sourceCounts.push({directSourceUrl:c.url,sourceUrl:c.url,platform:'amazon.com',provider:'bright_data_amazon_search',asin:c.asin,title:c.title||'Amazon',publicReviewCount:c.ratingCount??null,ratingEstimate:c.rating??null,individualExtractedCount:0,aggregateOnly:true,status:'found',matchConfidence:c.verificationConfidence,verificationMethod:'amazon_search+identity_verification',verificationReason:c.verificationReason||'',linkVerified:true,lensTabs:['amazon_search'],lensRank:null,discoveryOrigin:'amazon_high_volume'})}return{...rs,sourceCounts,aggregateOnlySources:aggregateOnly,amazonVolumeDiscovery:{queries:discovery.queries||[],diagnostics:discovery.diagnostics||{},candidates:discovery.candidates.map(c=>({asin:c.asin,url:c.url,title:c.title,ratingCount:c.ratingCount,verificationConfidence:c.verificationConfidence,verificationReason:c.verificationReason}))}}}
function relatedAmazonFallbackCandidates(discovery,limit=4){
  const diag=discovery?.diagnostics||{},shortlist=new Map((diag.shortlist||[]).map(x=>[String(x.asin||'').toUpperCase(),x])),rows=[];
  for(const e of diag.candidateEvaluations||[]){
    const asin=String(e?.asin||'').toUpperCase(),base=shortlist.get(asin)||{};
    const relation=String(e?.relation||'').toLowerCase(),confidence=Number(e?.confidence),lex=Number(e?.lexicalOverlap),visual=Number(e?.localVisual),ratingCount=Number(base.ratingCount??e.ratingCount);
    if(!asin||relation!=='similar')continue;
    if(!(confidence>=.9&&lex>=.25&&(visual>=.49||Number(e?.rankOnPage)<=5)))continue;
    rows.push({asin,url:`https://www.amazon.com/dp/${asin}`,title:e.title||base.title||'Amazon related antenna listing',ratingCount:Number.isFinite(ratingCount)&&ratingCount>0?ratingCount:null,rating:base.rating??null,verificationConfidence:Math.min(.78,Math.max(.62,.6+Math.min(.12,Math.max(0,lex-.25))+(visual>=.49?.04:0))),verificationRelation:'related_marketplace_fallback',verificationReason:`Related high-volume marketplace fallback after exact-source shortfall: verifier classified this as similar, not exact. Used only as review-style reference text, not as proof of identical product. ${clean(e.reason).slice(0,180)}`});
  }
  return rows.sort((a,b)=>(b.ratingCount||0)-(a.ratingCount||0)).slice(0,Math.max(0,limit));
}
function hasVerifiedAmazon(rs){return marketplaceSources(rs).some(x=>isAmazonV2(x.directSourceUrl||x.sourceUrl)&&verifiedSource(x))}
function hasManualAmazon(rs){return marketplaceSources(rs).some(x=>isAmazonV2(x.directSourceUrl||x.sourceUrl)&&x.discoveryOrigin==='manual_verified_amazon')}
function hasHighVolumeAmazon(rs){return marketplaceSources(rs).some(x=>isAmazonV2(x.directSourceUrl||x.sourceUrl)&&(x.discoveryOrigin==='amazon_high_volume'||x.provider==='bright_data_amazon_search'))}
function noCreditResult(x){const e=String(x?.error||'');return/bright_data_no_credits|insufficient[_\s-]*(?:credits?|balance)|positive credit balance|required.+credits|add funds|account is suspended/i.test(e)||classifyBrightDataFailure({status:x?.httpStatus||null,body:e,service:'dataset'})?.code==='bright_data_no_credits'}
function rankSources(rows){return[...rows].sort((a,b)=>{const av=sourceReviewVolume(a),bv=sourceReviewVolume(b);if(av!==bv)return bv-av;const ah=a.discoveryOrigin==='amazon_high_volume'||a.provider==='bright_data_amazon_search'?1:0,bh=b.discoveryOrigin==='amazon_high_volume'||b.provider==='bright_data_amazon_search'?1:0;if(ah!==bh)return bh-ah;const ac=Number(a.matchConfidence||a.sameProductConfidence||0),bc=Number(b.matchConfidence||b.sameProductConfidence||0);if(ac!==bc)return bc-ac;return String(host(a.directSourceUrl||a.sourceUrl)).localeCompare(String(host(b.directSourceUrl||b.sourceUrl)))})}
function allocateAmazonBudgets(sources,totalBudget){const rows=rankSources(sources),n=rows.length;if(!n||totalBudget<=0)return[];const budget=Math.max(0,Math.min(MAX_MARKETPLACE_PULLS,Math.floor(totalBudget))),floor=Math.min(MIN_AMAZON_PER_SOURCE,Math.max(1,Math.floor(budget/n)));let left=Math.max(0,budget-floor*n);const weights=rows.map(s=>Math.max(1,Math.sqrt(sourceReviewVolume(s)+1))),weightTotal=weights.reduce((a,b)=>a+b,0)||1;const out=rows.map((src,i)=>{const extra=Math.floor(left*weights[i]/weightTotal);return{src,budget:floor+extra}});let assigned=out.reduce((a,x)=>a+x.budget,0),cursor=0;while(assigned<budget&&out.length){out[cursor%out.length].budget++;assigned++;cursor++}return out.filter(x=>x.budget>0)}
function pullableAmazonSource(s){return verifiedSource(s)||(s?.discoveryOrigin==='amazon_high_volume'&&/related high-volume marketplace fallback/i.test(String(s?.verificationReason||''))&&sourceReviewVolume(s)>0)}
function selectPlan(rs,existingCount,marketplaceLimit=MAX_MARKETPLACE_PULLS){const all=marketplaceSources(rs),amazon=all.filter(x=>isAmazonV2(x.directSourceUrl||x.sourceUrl)&&pullableAmazonSource(x)),ebay=rankSources(all.filter(x=>/(^|\.)ebay\./i.test(host(x.directSourceUrl||x.sourceUrl))&&verifiedSource(x))).slice(0,3),available=Math.max(0,Math.min(marketplaceLimit,MAX_MARKETPLACE_PULLS)),ebayReserve=ebay.length&&available?(available<=20?Math.min(5,available):Math.min(30,Math.max(Math.min(10,available),Math.floor(available*.12)))):0,amazonBudget=Math.max(0,available-ebayReserve),amazonPlan=allocateAmazonBudgets(amazon,amazonBudget),ebayEach=ebay.length?Math.floor(ebayReserve/ebay.length):0;return{amazonPlan,ebayPlan:ebayEach?ebay.map(src=>({src,budget:ebayEach})):[],verifiedAmazonSources:amazon.filter(verifiedSource).length,pullableAmazonSources:amazon.length,totalPlanned:amazonPlan.reduce((n,x)=>n+x.budget,0)+ebayEach*ebay.length,existingCount,available,marketplaceLimit}}
function toReference(src,r,provider){const sourceUrl=src.directSourceUrl||src.sourceUrl||'',asin=clean(src.asin||amazonAsinV2(sourceUrl)||'').toUpperCase(),bodyText=clean(r.body);return{referenceId:`REF-${hash(`${sourceUrl}|${r.reviewId||''}|${bodyText}`).slice(0,8)}`,platform:host(sourceUrl)||src.platform||'',provider:provider||src.provider||'marketplace',sourceUrl,sourceAsin:asin,sourceListingTitle:clean(src.title||''),sourceRating:r.rating??null,sourceTitle:clean(r.title).slice(0,220),sourceBody:bodyText,sourceReviewId:r.reviewId||'',sourceVerifiedPurchase:Boolean(r.verifiedPurchase),sourceReviewDate:r.reviewDate||null,sourceAuthorName:clean(r.authorName).slice(0,160),wordCount:bodyText.split(/\s+/).filter(Boolean).length,sentenceCount:sent(bodyText)}}

export async function POST(req){
  let body;try{body=await req.json()}catch{return Response.json({error:'Invalid JSON body.'},{status:400})}
  let rs=body?.referenceSet;if(!rs||!Array.isArray(rs.references))return Response.json({error:'referenceSet is required.'},{status:400});
  const key=process.env.BRIGHT_DATA_API_KEY||'',balance=await getBrightDataBalance(key,{force:true});
  if(balance.noCredits)return Response.json({error:'Bright Data has insufficient credits/balance. Add funds in Bright Data, then retry marketplace enrichment.',code:'bright_data_no_credits',brightData:{stage:'marketplace_preflight',noCredits:true}},{status:402,headers:{'cache-control':'no-store'}});
  let discovery={candidates:[],queries:[],diagnostics:{skipped:false}};
  if(hasManualAmazon(rs))discovery={candidates:[],queries:[],diagnostics:{skipped:true,reason:'manual_amazon_listing_supplied'}};
  else{try{discovery=await discoverAmazonVolumeCandidates(req,rs)}catch(e){const msg=clean(e?.message||e);if(/bright_data_no_credits/i.test(msg))return Response.json({error:'Bright Data has insufficient credits/balance. Add funds in Bright Data, then retry marketplace enrichment.',code:'bright_data_no_credits',brightData:{stage:'amazon_volume_discovery'}},{status:402,headers:{'cache-control':'no-store'}});discovery={candidates:[],queries:[],diagnostics:{error:msg}}}const targetSourceCount=Number(body?.targetSourceCount||rs?.targetSourceCount)||5,existingAsins=new Set(marketplaceSources(rs).map(x=>amazonAsinV2(x.directSourceUrl||x.sourceUrl)).filter(Boolean)),candidateAsins=new Set((discovery.candidates||[]).map(x=>String(x.asin||'').toUpperCase()).filter(Boolean)),relatedNeed=Math.max(0,targetSourceCount-marketplaceSources(rs).length-candidateAsins.size);if(relatedNeed>0){const related=relatedAmazonFallbackCandidates(discovery,targetSourceCount).filter(x=>!existingAsins.has(String(x.asin||'').toUpperCase())&&!candidateAsins.has(String(x.asin||'').toUpperCase())).slice(0,relatedNeed);if(related.length)discovery={...discovery,candidates:[...(discovery.candidates||[]),...related],diagnostics:{...(discovery.diagnostics||{}),relatedMarketplaceFallback:{used:true,reason:'exact_source_shortfall',added:related.length,policy:'related_review_text_only'}}}}rs=augmentWithDiscoveredAmazon(rs,discovery)}
  const requestedLimit=Number(body?.maxMarketplaceReviews??rs?.referenceBudget?.maxMarketplaceReviews),marketplaceLimit=Math.max(1,Math.min(MAX_MARKETPLACE_PULLS,Math.floor(Number.isFinite(requestedLimit)&&requestedLimit>0?requestedLimit:MAX_MARKETPLACE_PULLS))),plan=selectPlan(rs,(rs.references||[]).length,marketplaceLimit),jobs=[...plan.amazonPlan.map(x=>({...x,type:'amazon'})),...plan.ebayPlan.map(x=>({...x,type:'ebay'}))];
  if(!jobs.length)return Response.json({referenceSet:{...rs,pulledReferences:Array.isArray(rs.pulledReferences)?rs.pulledReferences:[...(rs.references||[])],sourceReviewTextExported:true,marketplaceIngestion:{attemptedSources:0,verifiedAmazonSources:plan.verifiedAmazonSources,appendedReviews:0,pulledReviews:0,sources:[],amazonVolumeDiscovery:discovery.diagnostics||null,budget:{hardCap:marketplaceLimit,remainingCapacity:plan.available,planned:0}}}},{headers:{'cache-control':'no-store'}});
  const results=await Promise.all(jobs.map(async job=>{const {src,budget,type}=job;try{const result=type==='amazon'?await collectAmazonReviewsV2(src,{maxReviews:budget,maxBatches:1}):await ingestMarketplaceSource(src,{maxPages:3,maxReviews:budget});return{...job,result}}catch(e){return{...job,result:{reviews:[],provider:null,attempted:0,blocked:0,failed:1,error:clean(e?.message||e)}}}}));
  const creditFailure=results.find(x=>noCreditResult(x.result));if(creditFailure)return Response.json({error:'Bright Data has insufficient credits/balance. Add funds in Bright Data, then retry marketplace enrichment.',code:'bright_data_no_credits',brightData:{stage:'marketplace_dataset',sourceUrl:creditFailure.src?.directSourceUrl||creditFailure.src?.sourceUrl||null,detail:creditFailure.result?.error||null}},{status:402,headers:{'cache-control':'no-store'}});
  const sourceCounts=[...(rs.sourceCounts||[])],aggregateOnly=[...(rs.aggregateOnlySources||[])],existingExport=[...(Array.isArray(rs.pulledReferences)?rs.pulledReferences:rs.references||[])],existingBySource=existingSourceCounts(existingExport),pulled=[...existingExport],pulledKeys=new Set(existingExport.map(r=>bodyKey(r.sourceBody)).filter(Boolean)),diagnostics=[];
  for(const {src,result,budget,type} of results){const sourceUrl=src.directSourceUrl||src.sourceUrl||'',provider=result.provider||src.provider||'marketplace';let pulledFromSource=0;for(const r of result.reviews||[]){const ref=toReference(src,r,provider),k=bodyKey(ref.sourceBody);if(!k||pulledKeys.has(k)||pulled.length>=MAX_EXPORT_REFS)continue;pulledKeys.add(k);pulled.push(ref);pulledFromSource++}const existingFromSource=existingBySource.get(sourceKey(src))||existingBySource.get(sourceUrl.toLowerCase())||0,totalFromSource=existingFromSource+pulledFromSource;let row=sourceCounts.find(x=>sourceKey(x)===sourceKey(src));if(totalFromSource&&!row){row={...src,directSourceUrl:sourceUrl,sourceUrl:src.sourceUrl||sourceUrl,aggregateOnly:false,status:'found'};sourceCounts.push(row)}if(row){row.asin=row.asin||amazonAsinV2(sourceUrl)||'';row.individualExtractedCount=totalFromSource;row.extractedReviewCount=totalFromSource;row.reviewCount=totalFromSource;row.aggregateOnly=totalFromSource===0;row.provider=provider;row.status=totalFromSource?'found':(row.status||'found');if(result.itemFeedbackCount!=null){row.itemFeedbackCount=result.itemFeedbackCount;if(row.publicReviewCount==null)row.publicReviewCount=result.itemFeedbackCount}if(result.aggregateRatingCount!=null)row.publicReviewCount=result.aggregateRatingCount;if(result.aggregateRating!=null)row.ratingEstimate=result.aggregateRating;if(totalFromSource)row.error=null;else if(result.error)row.error=result.error}diagnostics.push({sourceUrl,asin:src.asin||amazonAsinV2(sourceUrl)||null,platform:host(sourceUrl)||src.platform||'',provider,type,budget,discoveryOrigin:src.discoveryOrigin||null,attempted:result.attempted||0,blocked:result.blocked||0,failed:result.failed||0,pending:Boolean(result.pending),snapshotId:result.snapshotId||result.batches?.[0]?.snapshotId||null,canonicalUrl:result.canonicalUrl||null,requested:result.requested??budget,itemId:result.itemId??null,itemScoped:Boolean(result.itemScoped),transport:result.transport??null,zoneSource:result.zoneSource??null,rawFeedbackCards:result.rawFeedbackCards??null,totalFeedbackCards:result.totalFeedbackCards??null,itemFeedbackCount:result.itemFeedbackCount??null,automatedExcluded:result.automatedExcluded??null,sellerWideExcluded:result.sellerWideExcluded??null,aggregateRatingCount:result.aggregateRatingCount??null,rawRows:result.rawRows??null,parsedBodies:result.parsedBodies??null,reviewIdCount:result.reviewIdCount??null,pulled:pulledFromSource,existing:existingFromSource,total:totalFromSource,error:result.error||''})}
  for(const row of sourceCounts){const sourceUrl=row.directSourceUrl||row.sourceUrl||'',existing=existingBySource.get(sourceKey(row))||existingBySource.get(sourceUrl.toLowerCase())||0,current=Math.max(0,Number(row.individualExtractedCount)||0,Number(row.extractedReviewCount)||0,Number(row.reviewCount)||0);if(existing>current){row.individualExtractedCount=existing;row.extractedReviewCount=existing;row.reviewCount=existing;row.aggregateOnly=false;row.status='found';row.error=null}}
  const generationExisting=[...(rs.references||[])],generationSeen=new Set(generationExisting.map(r=>bodyKey(r.sourceBody)).filter(Boolean)),generation=[...generationExisting];for(const r of pulled){if(generation.length>=MAX_GENERATION_REFS)break;const k=bodyKey(r.sourceBody);if(!k||generationSeen.has(k))continue;generationSeen.add(k);if(!generation.some(x=>x.referenceId===r.referenceId))generation.push(r)}
  const orderedSourceCounts=sortBestReviewSources(sourceCounts),generationReferences=interleaveReferencesBySource(generation,{limit:MAX_GENERATION_REFS}),active=new Set(generationReferences.map(r=>r.sourceUrl)),usableSources=orderedSourceCounts.filter(isUsableReviewSource),targetSourceCount=Number(body?.targetSourceCount||rs?.targetSourceCount)||5,out={...rs,references:generationReferences,pulledReferences:interleaveReferencesBySource(pulled,{limit:MAX_EXPORT_REFS}),sourceCounts:orderedSourceCounts,aggregateOnlySources:aggregateOnly.filter(x=>!active.has(x.directSourceUrl||x.sourceUrl)),platformCounts:recomputePlatformCounts(generationReferences),totalIndividualReviews:generationReferences.length,availableForGeneration:generationReferences.length,totalPulledReviews:Math.min(MAX_EXPORT_REFS,pulled.length),usableReviewSources:usableSources.length,matchedPages:orderedSourceCounts.length,verifiedSourceLinks:orderedSourceCounts.filter(x=>x.linkVerified).length,sourceReviewTextExported:true,sourceGate:{targetSourceCount,usableReviewSources:usableSources.length,status:usableSources.length>=targetSourceCount?'passed':'source_count_shortfall'},marketplaceIngestion:{attemptedSources:results.length,verifiedAmazonSources:plan.verifiedAmazonSources,appendedReviews:generation.length-generationExisting.length,pulledReviews:Math.min(MAX_EXPORT_REFS,pulled.length)-existingExport.length,sources:diagnostics,amazonVolumeDiscovery:discovery.diagnostics||null,budget:{hardCap:marketplaceLimit,remainingCapacity:plan.available,planned:plan.totalPlanned,amazonSources:plan.amazonPlan.map(x=>({asin:x.src.asin||amazonAsinV2(x.src.directSourceUrl||x.src.sourceUrl),url:x.src.directSourceUrl||x.src.sourceUrl,budget:x.budget,publicReviewCount:sourceReviewVolume(x.src)||null})),ebaySources:plan.ebayPlan.map(x=>({url:x.src.directSourceUrl||x.src.sourceUrl,budget:x.budget,publicReviewCount:sourceReviewVolume(x.src)||null}))}}};return Response.json({referenceSet:out},{headers:{'cache-control':'no-store'}})
}
