export const runtime='nodejs';
export const maxDuration=300;

import{withBrightLensNativeContext}from'../../../lib/bright-lens-native';
import{getBrightDataBalance,classifyBrightDataFailure,cleanBright}from'../../../lib/bright-data-status';
import{amazonAsinV2}from'../../../lib/amazon-review-ingest-v2';
import{referenceBudget}from'../../../lib/reference-pipeline.mjs';

const BD='https://api.brightdata.com';
let cachedZone=null;

function clean(x){return String(x||'').replace(/\s+/g,' ').trim()}
function host(x){try{return new URL(x).hostname.replace(/^www\./,'').toLowerCase()}catch{return''}}

async function accountPreflight(key){
  if(!key)return{ok:false,configured:false,httpStatus:null,error:'Bright Data Lens is not configured.',noCredits:false,balance:null};
  const balance=await getBrightDataBalance(key,{force:true});
  if(balance.noCredits)return{ok:false,configured:true,httpStatus:402,error:'bright_data_no_credits',message:'Bright Data has insufficient credits/balance. Add funds in Bright Data, then rescan.',noCredits:true,balance:balance.balance,pendingBalance:balance.pendingBalance};
  try{
    const r=await fetch(`${BD}/status`,{headers:{authorization:`Bearer ${key}`},cache:'no-store',signal:AbortSignal.timeout(12000)}),raw=await r.text();
    if(!r.ok){const f=classifyBrightDataFailure({status:r.status,body:raw,headers:r.headers,service:'account'});return{ok:false,configured:true,httpStatus:r.status,error:f?.code||`Bright Data account API ${r.status}: ${clean(raw).slice(0,180)}`,message:f?.message||null,noCredits:f?.code==='bright_data_no_credits',balance:balance.balance,pendingBalance:balance.pendingBalance}}
    if(/invalid status|not active|inactive|suspended/i.test(raw))return{ok:false,configured:true,httpStatus:r.status,error:'Bright Data account is not active.',noCredits:false,balance:balance.balance,pendingBalance:balance.pendingBalance};
    return{ok:true,configured:true,httpStatus:r.status,error:null,noCredits:false,balance:balance.balance,pendingBalance:balance.pendingBalance};
  }catch(e){return{ok:null,configured:true,httpStatus:null,error:`Bright Data account preflight failed: ${clean(e?.message||e).slice(0,180)}`,noCredits:false,balance:balance.balance,pendingBalance:balance.pendingBalance}}
}

async function getActiveZones(key){
  const r=await fetch(`${BD}/zone/get_active_zones`,{headers:{authorization:`Bearer ${key}`},cache:'no-store',signal:AbortSignal.timeout(15000)});
  const raw=await r.text();
  if(!r.ok){const f=classifyBrightDataFailure({status:r.status,body:raw,headers:r.headers,service:'account'});if(f)throw Error(`${f.code}:${f.message}`);throw Error(`Bright Data zone lookup HTTP ${r.status}: ${clean(raw).slice(0,220)}`)}
  let zones;try{zones=JSON.parse(raw)}catch{throw Error('Bright Data zone lookup returned invalid JSON.')}
  if(!Array.isArray(zones))throw Error('Bright Data zone lookup returned an unexpected response.');
  return zones;
}

async function resolveSerpZone(key){
  if(cachedZone)return{zone:cachedZone,source:'cache',activeSerpZones:[cachedZone]};
  const configured=clean(process.env.BRIGHT_DATA_SERP_ZONE),zones=await getActiveZones(key),serp=zones.filter(z=>String(z?.type||'').toLowerCase()==='serp'&&z?.name);
  if(configured){const match=serp.find(z=>z.name===configured);if(match){cachedZone=match.name;return{zone:match.name,source:'environment',activeSerpZones:serp.map(z=>z.name)}}}
  if(!serp.length)throw Error('Bright Data API key is valid, but this account has no active SERP API zone. Create or activate a SERP API zone in Bright Data, then rescan.');
  cachedZone=serp[0].name;return{zone:serp[0].name,source:'auto_detected',activeSerpZones:serp.map(z=>z.name)};
}

function recomputePlatformCounts(refs){const m=new Map();for(const r of refs||[]){const k=`${r.platform}|${r.provider||''}`,x=m.get(k)||{platform:r.platform,provider:r.provider,reviewCount:0,pages:new Set()};x.reviewCount++;x.pages.add(r.sourceUrl);m.set(k,x)}return[...m.values()].map(x=>({platform:x.platform,provider:x.provider,reviewCount:x.reviewCount,pageCount:x.pages.size})).sort((a,b)=>b.reviewCount-a.reviewCount)}
function stripOriginalStore(rs,originalProductUrl){const h=host(originalProductUrl);if(!h||!rs)return rs;rs.sourceCounts=(rs.sourceCounts||[]).filter(x=>host(x.directSourceUrl||x.sourceUrl)!==h);rs.aggregateOnlySources=(rs.aggregateOnlySources||[]).filter(x=>host(x.directSourceUrl||x.sourceUrl)!==h);rs.references=(rs.references||[]).filter(x=>host(x.sourceUrl)!==h);rs.pulledReferences=(rs.pulledReferences||rs.references||[]).filter(x=>host(x.sourceUrl)!==h);rs.platformCounts=recomputePlatformCounts(rs.references);rs.totalIndividualReviews=rs.references.length;rs.totalPulledReviews=rs.pulledReferences.length;rs.availableForGeneration=Math.min(250,rs.references.length);rs.matchedPages=rs.sourceCounts.length;rs.verifiedSourceLinks=rs.sourceCounts.filter(x=>x.linkVerified).length;return rs}
function manualAmazonReferenceSet(body,originalProductUrl){const raw=clean(body?.amazonListingUrl),asin=amazonAsinV2(raw);if(!raw)return null;if(!asin)throw Error('Known Amazon listing must contain a valid 10-character ASIN.');const budget=referenceBudget(body?.referenceBudget),sourceUrl=`https://www.amazon.com/dp/${asin}`,source={platform:'amazon.com',provider:'user_supplied_amazon_listing',sourceUrl,directSourceUrl:sourceUrl,asin,title:'User-supplied Amazon listing',status:'found',matchConfidence:1,confidence:'high',publicReviewCount:null,extractedReviewCount:0,individualExtractedCount:0,pageCount:1,aggregateOnly:true,ratingEstimate:null,error:null,linkVerified:true,linkVerification:'user_supplied_amazon_listing',lensTabs:['manual_amazon_listing'],lensRank:null,verificationMethod:'user_supplied_amazon_listing',verificationReason:'Amazon listing supplied directly for this product scan.',discoveryOrigin:'manual_verified_amazon'};return{version:'individual-reference-v13',provider:'user_supplied_amazon_listing',referenceBudget:budget,productUrl:originalProductUrl,productTitle:clean(body?.productTitle),productDescription:clean(body?.productDescription),references:[],pulledReferences:[],sourceCounts:[source],aggregateOnlySources:[],platformCounts:[],totalIndividualReviews:0,totalPulledReviews:0,availableForGeneration:0,confidence:'high',matchedPages:1,verifiedSourceLinks:1,lensDiscovery:{enabled:false,status:'skipped',reason:'user_supplied_amazon_listing',budget},provenance:{manualAmazonListing:true,originalProductUrl,amazonListingUrl:sourceUrl},syntheticUseOnly:true,sourceReviewTextExported:true}}

function providerStatus(x){return{configured:Boolean(x?.configured),ok:x?.ok??null,httpStatus:x?.httpStatus??null,noCredits:Boolean(x?.noCredits),error:x?.error?cleanBright(x.error).slice(0,180):null}}
function safeCandidate(x){return{platform:clean(x?.platform).slice(0,100)||null,url:x?.url||null,asin:clean(x?.asin).slice(0,10)||null,title:clean(x?.title).slice(0,180)||null,merchant:clean(x?.merchant).slice(0,120)||null,lensTabs:Array.isArray(x?.lensTabs)?x.lensTabs.slice(0,3):[],lensRank:x?.lensRank??null,lensScore:x?.lensScore??null,imageHits:x?.imageHits??null,candidateImageAvailable:Boolean(x?.candidateImageAvailable),localVisualScore:x?.localVisualScore??null,localDifferenceHash:x?.localDifferenceHash??null,localSilhouetteIou:x?.localSilhouetteIou??null,lexicalOverlap:x?.lexicalOverlap??null,aiConfidence:x?.aiConfidence??null,matchScore:x?.matchScore??null,accepted:Boolean(x?.accepted),verificationMethod:clean(x?.verificationMethod).slice(0,100)||null,verificationReason:clean(x?.verificationReason).slice(0,260)||null}}
function safeAmazonRow(x){return{asin:clean(x?.asin).slice(0,10)||null,title:clean(x?.title).slice(0,180)||null,ratingCount:x?.ratingCount??null,rankOnPage:x?.rankOnPage??null,pageNumber:x?.pageNumber??null,lexicalOverlap:x?.lexicalOverlap??null,discoveryScore:x?.discoveryScore??null,localVisual:x?.localVisual??null,sameProduct:x?.sameProduct??null,confidence:x?.confidence??null,relation:clean(x?.relation).slice(0,80)||null,reason:clean(x?.reason).slice(0,260)||null,eligible:x?.eligible??null,reasons:Array.isArray(x?.reasons)?x.reasons.slice(0,8):[]}}
function safeTransport(rows){return(rows||[]).slice(0,12).map(x=>({image:clean(x?.image).slice(0,220)||null,tab:clean(x?.tab).slice(0,60)||null,error:cleanBright(x?.error||'').slice(0,220)||null,upload:x?.upload||null,result:x?.result||null}))}
function emptyScanDiagnostic(rs,transport,preflight){
  const l=rs?.lensDiscovery||{},v=rs?.verificationDiagnostics||{},a=rs?.amazonFallbackDiscovery||{},ad=a?.diagnostics||{},base=rs?.lensFailureDiagnostics||null;
  return{version:'reference-scan-diagnostic-v1',stage:'empty_verified_source_set',provider:providerStatus(preflight),budget:rs?.referenceBudget||l?.budget||null,lens:{status:l.status||null,baseFailureStage:base?.stage||null,sourceImages:Array.isArray(l.sourceImages)?l.sourceImages.length:(base?.lens?.sourceImages??null),requests:l.requests??l.lensRequests??base?.lens?.requests??null,succeeded:l.succeeded??base?.lens?.succeeded??null,failed:l.failed??base?.lens?.failed??null,rawResults:l.rawResults??base?.lens?.rawResults??null,uniqueCandidates:l.uniqueCandidates??base?.lens?.uniqueCandidates??null,acceptedCandidates:l.acceptedCandidates??null,rejectedCandidates:l.rejectedCandidates??null,amazonCandidates:l.amazonCandidates??null,amazonAccepted:l.amazonAccepted??null,tabs:l.tabs||base?.lens?.tabs||null,candidateSample:(l.candidateSample||[]).slice(0,12).map(safeCandidate),transport:safeTransport(transport)},verification:{candidates:v.candidates??null,accepted:v.accepted??null,selected:v.selected??null,rejected:v.rejected??null,exactAccepted:v.exactAccepted??null,productAccepted:v.productAccepted??null,visualOnlyAccepted:v.visualOnlyAccepted??null,candidateSample:(v.candidateSample||[]).slice(0,12).map(safeCandidate),rejectedCandidates:(v.rejectedCandidates||[]).slice(0,12).map(safeCandidate)},amazonFallback:{status:a.status||null,baseLensError:clean(a.baseLensError).slice(0,220)||null,error:clean(ad.error).slice(0,220)||null,queries:Array.isArray(a.queries)?a.queries.slice(0,5).map(x=>clean(x).slice(0,180)):[],queryMode:ad.queryMode||null,verificationError:clean(ad.verificationError).slice(0,220)||null,referenceImageUsed:Boolean(ad.referenceImageUsed),localReferenceImageUsed:Boolean(ad.localReferenceImageUsed),localVisualFallbackUsed:Boolean(ad.localVisualFallbackUsed),searchRuns:(ad.searchRuns||[]).slice(0,5).map(x=>({keyword:clean(x?.keyword).slice(0,180),ok:Boolean(x?.ok),rawRows:x?.rawRows??null,resultCount:x?.resultCount??null,error:clean(x?.error).slice(0,180)||null})),shortlist:(ad.shortlist||[]).slice(0,12).map(safeAmazonRow),candidateEvaluations:(ad.candidateEvaluations||[]).slice(0,12).map(safeAmazonRow),deterministicRescueAssessments:(ad.deterministicRescueAssessments||[]).slice(0,12).map(safeAmazonRow),verified:(ad.verified||[]).slice(0,4).map(safeAmazonRow)}};
}
function logEmptyScan(diagnosticId,productUrl,d){console.warn('[reference-scan-empty]',JSON.stringify({diagnosticId,productHost:host(productUrl),budget:d?.budget?.id||null,provider:d?.provider||null,lens:{requests:d?.lens?.requests,succeeded:d?.lens?.succeeded,failed:d?.lens?.failed,rawResults:d?.lens?.rawResults,uniqueCandidates:d?.lens?.uniqueCandidates,acceptedCandidates:d?.lens?.acceptedCandidates},verification:{candidates:d?.verification?.candidates,accepted:d?.verification?.accepted,rejected:d?.verification?.rejected,rejectedCandidates:(d?.verification?.rejectedCandidates||[]).slice(0,6)},amazonFallback:{status:d?.amazonFallback?.status,queryMode:d?.amazonFallback?.queryMode,verificationError:d?.amazonFallback?.verificationError,shortlist:(d?.amazonFallback?.shortlist||[]).slice(0,6),candidateEvaluations:(d?.amazonFallback?.candidateEvaluations||[]).slice(0,6)}}))}

export async function POST(req){
  let body;try{body=await req.json()}catch{return Response.json({error:'Invalid JSON body.'},{status:400})}
  const diagnosticId=`ref-${crypto.randomUUID()}`;
  const originalProductUrl=String(body?.productUrl||'').trim();if(!originalProductUrl)return Response.json({error:'Product URL is required.'},{status:400});
  let manual;try{manual=manualAmazonReferenceSet(body,originalProductUrl)}catch(e){return Response.json({error:e?.message||String(e)},{status:400,headers:{'cache-control':'no-store'}})}if(manual)return Response.json({referenceSet:manual},{headers:{'cache-control':'no-store'}});
  const key=process.env.BRIGHT_DATA_API_KEY||'',providerPreflight=await accountPreflight(key),provider=providerStatus(providerPreflight);
  if(providerPreflight.noCredits)return Response.json({error:'Bright Data has insufficient credits/balance. Add funds in Bright Data, then rescan.',code:'bright_data_no_credits',diagnosticId,brightData:{stage:'account_preflight',provider}},{status:402,headers:{'cache-control':'no-store'}});
  let zoneInfo={zone:clean(process.env.BRIGHT_DATA_SERP_ZONE)||null,source:'not_resolved',activeSerpZones:[]},lensUnavailableReason=null;
  if(providerPreflight.ok===false)lensUnavailableReason=providerPreflight.error;
  else if(key){try{zoneInfo=await resolveSerpZone(key);process.env.BRIGHT_DATA_SERP_ZONE=zoneInfo.zone}catch(e){lensUnavailableReason=e?.message||String(e)}}
  else lensUnavailableReason='Bright Data Lens is not configured.';
  if(/bright_data_no_credits/i.test(String(lensUnavailableReason||'')))return Response.json({error:'Bright Data has insufficient credits/balance. Add funds in Bright Data, then rescan.',code:'bright_data_no_credits',diagnosticId,brightData:{stage:'zone_resolution',provider}},{status:402,headers:{'cache-control':'no-store'}});
  const forwardedBody={...body,...(lensUnavailableReason?{_lensUnavailableReason:lensUnavailableReason}:{})},forwarded=new Request(req.url,{method:'POST',headers:req.headers,body:JSON.stringify(forwardedBody)});
  const mod=await import('../reference-scan-v12/route.js');
  const transportDiagnostics=[];
  let res;
  try{
    res=lensUnavailableReason?await mod.POST(forwarded):await withBrightLensNativeContext({referer:originalProductUrl,diagnostics:transportDiagnostics},()=>mod.POST(forwarded));
  }catch(e){const msg=cleanBright(e?.message||e),f=classifyBrightDataFailure({body:msg,service:'dataset'}),diagnostics={version:'reference-scan-diagnostic-v1',stage:'discovery_exception',provider,lens:{transport:safeTransport(transportDiagnostics)}};if(f?.code==='bright_data_no_credits'||/bright_data_no_credits/i.test(msg))return Response.json({error:'Bright Data has insufficient credits/balance. Add funds in Bright Data, then rescan.',code:'bright_data_no_credits',diagnosticId,brightData:{stage:'discovery_exception',zone:zoneInfo.zone,zoneSource:zoneInfo.source,provider},diagnostics},{status:402,headers:{'cache-control':'no-store'}});return Response.json({error:`Reference discovery failed: ${msg}`,diagnosticId,brightData:{stage:'discovery_exception',zone:zoneInfo.zone,zoneSource:zoneInfo.source,provider},diagnostics},{status:400,headers:{'cache-control':'no-store'}})}
  let json;try{json=await res.clone().json()}catch{return res}
  if(res.ok&&json?.referenceSet){
    json.referenceSet.productUrl=originalProductUrl;
    json.referenceSet=stripOriginalStore(json.referenceSet,originalProductUrl);
    json.referenceSet.provenance={...(json.referenceSet.provenance||{}),diagnosticId,imageTransport:lensUnavailableReason?'lens_skipped':'bright_data_uploadbyurl_primary',originalProductUrl,provider};
    json.referenceSet.lensDiscovery={...(json.referenceSet.lensDiscovery||{}),transport:lensUnavailableReason?'skipped_provider_unavailable':'uploadbyurl_primary'};
    const lens=json.referenceSet.lensDiscovery||{},prov=json.referenceSet.provenance||{},lensRaw=Number(lens.rawResults??prov.lensRawResults??0),lensAccepted=Number(lens.acceptedCandidates??lens.verifiedAcceptedCandidates??prov.selectedSources??0),amazonFallbackAfterZeroLens=Boolean(prov.amazonFallbackUsed&&lensRaw===0&&lensAccepted===0);
    const requestedSourceCount=Math.max(1,Number(body?.targetSourceCount)||5),fallbackOnly=Boolean(prov.lensFailed||json.referenceSet.provider==='amazon_fallback_after_lens_error'||lens.status==='failed'||amazonFallbackAfterZeroLens);
    if(fallbackOnly&&requestedSourceCount>1&&!body?.allowAmazonFallbackOnly){const d=emptyScanDiagnostic(json.referenceSet,transportDiagnostics,providerPreflight),fallbackCount=(json.referenceSet.sourceCounts||[]).length,providerReason=lensUnavailableReason||d.lens?.transport?.[0]?.error||d.amazonFallback?.baseLensError||d.amazonFallback?.error||null;logEmptyScan(diagnosticId,originalProductUrl,d);return Response.json({error:`Lens source discovery failed before the app could verify ${requestedSourceCount} external sources. Amazon fallback found ${fallbackCount} aggregate-only source${fallbackCount===1?'':'s'}, but that is not a valid Lens/source scan.${providerReason?` Provider diagnostic: ${providerReason}`:''}`,code:'lens_source_discovery_failed',diagnosticId,brightData:{stage:'lens_source_discovery_failed',zone:zoneInfo.zone,zoneSource:zoneInfo.source,imageTransport:lensUnavailableReason?'lens_skipped':'bright_data_uploadbyurl_primary',provider},diagnostics:d},{status:400,headers:{'cache-control':'no-store'}})}
    if(!(json.referenceSet.sourceCounts||[]).length){const d=emptyScanDiagnostic(json.referenceSet,transportDiagnostics,providerPreflight),t=d.lens?.transport?.[0]||{},providerReason=lensUnavailableReason||t.error||d.amazonFallback?.error||d.amazonFallback?.verificationError||null;logEmptyScan(diagnosticId,originalProductUrl,d);if(/bright_data_no_credits/i.test(String(providerReason||'')))return Response.json({error:'Bright Data has insufficient credits/balance. Add funds in Bright Data, then rescan.',code:'bright_data_no_credits',diagnosticId,brightData:{stage:'empty_verified_source_set',zone:zoneInfo.zone,zoneSource:zoneInfo.source,provider},diagnostics:d},{status:402,headers:{'cache-control':'no-store'}});return Response.json({error:`Reference scan returned no verified external sources after Lens and Amazon fallback.${providerReason?` Provider diagnostic: ${providerReason}`:''}`,diagnosticId,brightData:{stage:'empty_verified_source_set',zone:zoneInfo.zone,zoneSource:zoneInfo.source,imageTransport:lensUnavailableReason?'lens_skipped':'bright_data_uploadbyurl_primary',provider},diagnostics:d},{status:400,headers:{'cache-control':'no-store'}})}
    return Response.json(json,{status:res.status,headers:{'cache-control':'no-store'}})
  }
  return Response.json({...json,diagnosticId,brightData:{...(json?.brightData||{}),provider,zone:zoneInfo.zone,zoneSource:zoneInfo.source}},{status:res.status,headers:{'cache-control':'no-store'}})
}
