export const runtime='nodejs';
export const maxDuration=300;

import{POST as v11POST}from'../reference-scan-v11/route';
import{discoverAmazonVolumeCandidates}from'../../../lib/amazon-volume-discovery-v2';
import{referenceBudget}from'../../../lib/reference-pipeline.mjs';

function cloneHeaders(h){const out=new Headers();for(const [k,v] of h.entries())out.set(k,v);return out}
function clean(x){return String(x??'').toLowerCase().replace(/[^a-z0-9°+ ]+/g,' ').replace(/\s+/g,' ').trim()}
function sourceRow(c){return{platform:'amazon.com',provider:'bright_data_amazon_search',sourceUrl:c.url,directSourceUrl:c.url,asin:c.asin,title:c.title||'Amazon',status:'aggregate_only',matchConfidence:Number((c.verificationConfidence||0).toFixed(3)),confidence:(c.verificationConfidence||0)>=.82?'high':'medium',publicReviewCount:c.ratingCount??null,countKind:c.ratingCount!=null?'amazon_search':null,extractedReviewCount:0,individualExtractedCount:0,pageCount:1,aggregateOnly:true,ratingEstimate:c.rating??null,error:null,linkVerified:true,linkVerification:c.verificationRelation==='deterministic_multimodal_rescue'?'amazon_search+local_multimodal_verification':'amazon_search+identity_verification',lensTabs:['amazon_search_fallback'],lensRank:null,verificationMethod:c.verificationRelation==='deterministic_multimodal_rescue'?'amazon_search+local_multimodal_verification':'amazon_search+identity_verification',verificationReason:c.verificationReason||null,discoveryOrigin:'amazon_high_volume'}}
function emptyReferenceSet(body,baseError){const budget=referenceBudget(body?.referenceBudget);return{version:'individual-reference-v13',provider:'amazon_fallback_after_lens_error',referenceBudget:budget,productUrl:String(body?.productUrl||''),productTitle:String(body?.productTitle||''),productDescription:String(body?.productDescription||''),references:[],pulledReferences:[],sourceCounts:[],aggregateOnlySources:[],platformCounts:[],totalIndividualReviews:0,totalPulledReviews:0,availableForGeneration:0,confidence:'none',matchedPages:0,verifiedSourceLinks:0,lensDiscovery:{enabled:true,status:'failed',error:baseError||null,budget},provenance:{lensFailed:true,amazonFallbackAttempted:true},syntheticUseOnly:true,sourceReviewTextExported:true}}
function markerCompatibility(reference,candidate){const r=clean(reference),c=clean(candidate),re=(x,s)=>new RegExp(`(?:^|\\s)(?:${x})(?:$|\\s)`).test(s);const rOutdoor=re('outdoor',r),rIndoor=re('indoor',r),cOutdoor=re('outdoor',c),cIndoor=re('indoor',c);if(rOutdoor&&!rIndoor&&cIndoor&&!cOutdoor)return{ok:false,reason:'indoor_outdoor_contradiction'};if(rIndoor&&!rOutdoor&&cOutdoor&&!cIndoor)return{ok:false,reason:'indoor_outdoor_contradiction'};const groups=[{ref:/omni|360°?|omnidirectional|omni directional/,cand:/omni|360°?|omnidirectional|omni directional/,name:'omnidirectional'},{ref:/magnetic base/,cand:/magnetic base/,name:'magnetic_base'},{ref:/directional/,cand:/directional/,name:'directional'}];for(const g of groups)if(g.ref.test(r)&&!g.cand.test(c))return{ok:false,reason:`missing_${g.name}`};return{ok:true,reason:'compatible'}}
function deterministicRescue(discovery,reference){const list=discovery?.diagnostics?.shortlist||[],out=[];for(const x of list){const visual=Number(x.localVisual),lex=Number(x.lexicalOverlap),rank=Number(x.rankOnPage),page=Number(x.pageNumber)||1;if(!x.asin||!Number.isFinite(visual)||visual<.52||!Number.isFinite(lex)||lex<.25||!Number.isFinite(rank)||rank>5||page>2)continue;const comp=markerCompatibility(reference,x.title||'');if(!comp.ok)continue;const confidence=Math.min(.89,.82+(visual-.52)*.45+Math.min(.025,Math.max(0,lex-.25)*.08));out.push({asin:x.asin,url:`https://www.amazon.com/dp/${x.asin}`,title:x.title||'Amazon',ratingCount:x.ratingCount??null,rating:null,verificationConfidence:confidence,verificationRelation:'deterministic_multimodal_rescue',verificationReason:`AI verifier unavailable; deterministic cross-check passed: Amazon search rank ${rank}, lexical overlap ${(lex*100).toFixed(0)}%, local image similarity ${visual.toFixed(3)}, and no major product-form contradiction.`})}return out.sort((a,b)=>(b.verificationConfidence-a.verificationConfidence)||((b.ratingCount||0)-(a.ratingCount||0))).slice(0,2)}

async function amazonFallback(req,body,rs,baseError){
  const discoveryInput={...(rs||{}),productDescription:body.productDescription||rs?.productDescription||'',productTitle:body.productTitle||rs?.productTitle||'',productUrl:body.productUrl||rs?.productUrl||''};
  let discovery;try{discovery=await discoverAmazonVolumeCandidates(req,discoveryInput)}catch(e){discovery={candidates:[],queries:[],diagnostics:{error:e?.message||String(e)}}}
  const baseRs=rs||emptyReferenceSet(body,baseError),identityTitle=discovery.identity?.title||baseRs.productTitle,referenceText=[identityTitle,discoveryInput.productDescription,discovery?.identity?.description||''].filter(Boolean).join(' '),normal=discovery.candidates||[],rescued=normal.length?[]:deterministicRescue(discovery,referenceText),candidates=normal.length?normal:rescued;
  if(!candidates.length)return Response.json({referenceSet:{...baseRs,productTitle:identityTitle,productDescription:discoveryInput.productDescription,amazonFallbackDiscovery:{status:'no_verified_candidate',baseLensError:baseError||null,queries:discovery.queries||[],identity:discovery.identity||null,diagnostics:{...(discovery.diagnostics||{}),deterministicRescueAttempted:true,deterministicRescueCandidates:rescued.length}}}},{headers:{'cache-control':'no-store'}});
  const rows=candidates.map(sourceRow),aggregate=rows.map(x=>({platform:x.platform,provider:x.provider,sourceUrl:x.sourceUrl,directSourceUrl:x.directSourceUrl,asin:x.asin,sameProductConfidence:x.matchConfidence,reviewCountEstimate:x.publicReviewCount,ratingEstimate:x.ratingEstimate,lensTabs:x.lensTabs,verificationMethod:x.verificationMethod}));
  const out={...baseRs,productTitle:identityTitle,productDescription:discoveryInput.productDescription,sourceCounts:rows,aggregateOnlySources:aggregate,confidence:rows.some(x=>x.confidence==='high')?'high':'medium',matchedPages:rows.length,verifiedSourceLinks:rows.length,amazonFallbackDiscovery:{status:rescued.length?'verified_deterministic_rescue':'verified',baseLensError:baseError||null,queries:discovery.queries||[],identity:discovery.identity||null,diagnostics:{...(discovery.diagnostics||{}),deterministicRescueUsed:Boolean(rescued.length)},candidates:candidates.map(c=>({asin:c.asin,url:c.url,title:c.title,ratingCount:c.ratingCount,verificationConfidence:c.verificationConfidence,verificationRelation:c.verificationRelation,verificationReason:c.verificationReason}))},provenance:{...(baseRs.provenance||{}),amazonFallbackUsed:true,amazonFallbackCandidates:rows.length,deterministicMultimodalRescue:Boolean(rescued.length)}};
  return Response.json({referenceSet:out},{headers:{'cache-control':'no-store'}})
}

export async function POST(req){
  let body;try{body=await req.json()}catch{return Response.json({error:'Invalid JSON body.'},{status:400})}
  if(body?._lensUnavailableReason)return amazonFallback(req,body,null,String(body._lensUnavailableReason));
  const forwarded=new Request(req.url,{method:'POST',headers:cloneHeaders(req.headers),body:JSON.stringify(body)});
  let baseRes,base;try{baseRes=await v11POST(forwarded);try{base=await baseRes.clone().json()}catch{base=null}}catch(e){return amazonFallback(req,body,null,e?.message||String(e))}
  if(!baseRes.ok)return amazonFallback(req,body,null,base?.error||`Lens HTTP ${baseRes.status}`);
  const rs=base?.referenceSet;if(!rs)return amazonFallback(req,body,null,'Lens response contained no referenceSet.');
  if((rs.sourceCounts||[]).length)return baseRes;
  return amazonFallback(req,body,rs,null)
}
