import {createHash,timingSafeEqual} from 'node:crypto';
import {WebSocket} from 'undici';
export const runtime='nodejs';export const dynamic='force-dynamic';export const maxDuration=300;
const HASH='8940a885ae6e50aca994e11f0fe4d53dbcf4508326238f344a4a37be740b1979',EXPIRES=Date.parse('2026-09-10T12:00:00Z'),AUTHOR='blvckledge',PID='1240448194984546305',SOURCE='blvckledge-archive-d027480bd6806441c9f0ea77e53725ab',STORE='https://plcqypajqvtpnjctdlho.supabase.co/functions/v1/blvckledge-history-store';
const H={'cache-control':'private, no-store','x-robots-tag':'noindex','referrer-policy':'no-referrer'},hash=x=>createHash('sha256').update(String(x)).digest('hex'),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const QUERY='from:blvckledge since:2025-03-03 until:2025-04-17',URL='https://site.twstalker.com/search/'+encodeURIComponent(QUERY),SEARCH_KEY=hash(QUERY);
function xid(x){return typeof x==='string'&&/^\d{8,24}$/.test(x)?x:null}
function clean(v){return String(v||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/[ \t]+/g,' ').trim()}
function rowsFrom(body,page){const out=[];for(const[k,t]of Object.entries(body?.tweets||{})){const id=xid(k)||xid(t?.id_str);if(!id||String(t?.core?.screen_name||'').toLowerCase()!==AUTHOR)continue;const date=Date.parse(t.created_at),parent=xid(t.in_reply_to_status_id_str),conv=xid(t.conversation_id_str),text=[t.note_tweet?.note_tweet_results?.result?.text,t.full_text,t.text].filter(x=>typeof x==='string').sort((a,b)=>b.length-a.length)[0]||'';out.push({id,source_job:SOURCE,author_handle:AUTHOR,is_authored_by_target:true,content_kind:t.is_retweet?'repost':parent?'reply':t.is_quote_status?'quote_post':conv&&conv!==id?'reply':'post',text:clean(text),url:'https://x.com/'+AUTHOR+'/status/'+id,published_at:Number.isFinite(date)?new Date(date).toISOString():null,parent_post_id:parent,conversation_id:conv,article_urls:[],raw:{...t,id_str:id,target:AUTHOR,source_surface:'date_filtered_search',search_query:QUERY,search_page:page}})}return out}
function cardRows(cards,surface){return cards.map(c=>{const d=new Date(Number((BigInt(c.id)>>22n)+1288834974657n)).toISOString();return{id:c.id,source_job:SOURCE,author_handle:AUTHOR,is_authored_by_target:true,content_kind:'unclassified',text:c.text,url:'https://x.com/'+AUTHOR+'/status/'+c.id,published_at:d,parent_post_id:null,conversation_id:null,article_urls:[],raw:{id_str:c.id,core:{screen_name:AUTHOR},full_text:c.text,created_at:d,timestamp_source:'x_snowflake',text_completeness:'unverified_seed_html',source_surface:surface,html:c.html}}})}
const PARSE=`function parse(doc){return [...doc.querySelectorAll('#tweets-tabs > .activity-posts')].map(card=>{const a=card.querySelector('.user-text3 a[href*="/status/"]'),m=a?.getAttribute('href')?.match(/^\\/blvckledge\\/status\\/(\\d+)$/i);if(!m)return null;return{id:m[1],text:[...card.querySelectorAll(':scope > .activity-descp > p')].map(p=>p.textContent).join('\\n').trim(),html:card.outerHTML}}).filter(Boolean)}`;
export async function GET(req){
 const began=Date.now(),q=new globalThis.URL(req.url).searchParams,token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||q.get('ticket')||'',want=Number(q.get('pages')||20);
 if(!token||Date.now()>EXPIRES||!timingSafeEqual(createHash('sha256').update(token).digest(),Buffer.from(HASH,'hex')))return new Response('Not found',{status:404,headers:H});if(!Number.isInteger(want)||want<1||want>20)return Response.json({error:'page_limit'},{status:400,headers:H});
 const key=process.env.BRIGHT_DATA_API_KEY||'';let password='',ws,newPosts=0,total=null,processed=0,lastDate=null,lastPage=null,stopReason='batch_limit';const pending=new Map();let seq=0;
 function safe(e){let t=String(e?.message||e);for(const s of[key,password,token])if(s)t=t.split(s).join('[REDACTED]');return t.slice(0,1000)}
 async function http(url,auth,body){const r=await fetch(url,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer '+auth,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),cache:'no-store',signal:AbortSignal.timeout(35000)});const t=await r.text();if(!r.ok)throw Error('HTTP '+r.status+': '+t.slice(0,500));return t?JSON.parse(t):null}
 const bd=p=>http('https://api.brightdata.com'+p,key),store=b=>http(STORE,token,b);
 async function save(mode,page,cursor,next,body,rows,extra={}){const id='blvh_'+hash(mode+':'+SEARCH_KEY+':'+page+':'+cursor).slice(0,32),dates=rows.map(r=>r.published_at).filter(Boolean).sort(),record={id,request:{target:AUTHOR,mode,search_key:mode==='profile_seed_repair'?hash('profile_seed'):SEARCH_KEY,query:QUERY,page,cursor,url:URL,profile_id:PID},status:'complete',record_count:rows.length,raw_records:[body],diagnostics:{page,cursor:next,has_more:Boolean(next),oldest:dates[0]||null,newest:dates.at(-1)||null,authored:rows.length,source_exhausted:false,...extra}};const result=await store({op:'commit',page:record,rows});newPosts+=result.new_posts;total=result.stored_posts;if(dates.length)lastDate=dates[0];lastPage=page;return record}
 try{
  const previous=(await store({op:'checkpoint',search_key:SEARCH_KEY}))?.[0];if(previous?.diagnostics?.source_exhausted)return Response.json({status:'search_exhausted',previous:previous.diagnostics},{headers:H});
  const account=await bd('/status'),creds=await bd('/zone/passwords?zone=nate_archive_browser');password=creds.passwords?.[0]||'';if(!account.customer||!password)throw Error('No browser credentials');ws=new WebSocket('wss://brd.superproxy.io:9222',{headers:{Authorization:'Basic '+Buffer.from('brd-customer-'+account.customer+'-zone-nate_archive_browser:'+password).toString('base64')}});
  ws.addEventListener('message',async e=>{let m;try{m=JSON.parse(typeof e.data==='string'?e.data:await e.data.text())}catch{return}if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}});
  await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('connect_timeout')),25000);ws.addEventListener('open',()=>{clearTimeout(t);resolve()},{once:true});ws.addEventListener('error',()=>{clearTimeout(t);reject(Error('connect_failed'))},{once:true})});
  const send=(method,params={},sessionId)=>new Promise((resolve,reject)=>{const id=++seq,timer=setTimeout(()=>{pending.delete(id);reject(Error('timeout:'+method))},method==='Page.navigate'?120000:55000);pending.set(id,{resolve,reject,timer});ws.send(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})}))});
  const target=await send('Target.createTarget',{url:'about:blank'}),attached=await send('Target.attachToTarget',{targetId:target.targetId,flatten:true}),cmd=(m,p={})=>send(m,p,attached.sessionId);await cmd('Page.enable');await cmd('Runtime.enable');await cmd('Page.navigate',{url:URL});
  let ready=false;for(let i=0;i<50;i++){const ev=await cmd('Runtime.evaluate',{expression:'({query:document.querySelector(".add-nw-event")?.getAttribute("data-query"),title:document.title})',returnByValue:true});if(ev.result?.value?.query===QUERY){ready=true;break}await sleep(600)}if(!ready)throw Error('Historical search page not ready');
  const ev=await cmd('Runtime.evaluate',{expression:`(()=>{${PARSE};const button=document.querySelector('.add-nw-event');return{cards:parse(document),html:document.documentElement.outerHTML,cursor:button?.getAttribute('data-cursor'),page:Number(button?.getAttribute('data-ec')||2)}})()`,returnByValue:true});const seed=ev.result?.value;if(!seed?.cursor)throw Error('Missing search cursor');
  if(!previous){const rs=cardRows(seed.cards,'historical_search_seed');await save('historical_search_seed',1,'',seed.cursor,{html:seed.html,cards:seed.cards},rs,{seed_post_ids:rs.map(r=>r.id),text_completeness:'unverified_seed_html'})}
  const profileDone=await store({op:'checkpoint',search_key:hash('profile_seed')});if(!profileDone?.length){const old=(await store({op:'profile_seed'}))?.[0]?.raw_records?.[0]?.html;if(old){const pp=await cmd('Runtime.evaluate',{expression:`(()=>{${PARSE};const doc=new DOMParser().parseFromString(${JSON.stringify(old)},'text/html');return parse(doc)})()`,returnByValue:true});const rs=cardRows(pp.result?.value||[],'original_profile_seed_repair');await save('profile_seed_repair',1,'',null,{original_profile_seed:true,cards:pp.result?.value},rs,{seed_post_ids:rs.map(r=>r.id)})}}
  let page=previous?Number(previous.request.page)+1:seed.page,cursor=previous?.diagnostics?.cursor||seed.cursor;const seen=new Set([cursor]);
  for(let n=0;n<want;n++,page++){
   if(Date.now()-began>205000){stopReason='time_checkpoint';break}let result,body,refreshes=[];const original=cursor;
   for(let a=0;a<5;a++){
    const form=new URLSearchParams({page:String(page),cursor,data:QUERY,action:'search'}).toString(),expression='(async()=>{const r=await fetch("/service/api",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/x-www-form-urlencoded; charset=UTF-8","X-Requested-With":"XMLHttpRequest"},body:'+JSON.stringify(form)+',signal:AbortSignal.timeout(22000)});return{status:r.status,text:await r.text()}})()';
    const r=await cmd('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails){await sleep(1000);continue}result=r.result?.value;try{body=JSON.parse(result?.text||'')}catch{body=null}if(result?.status===201&&body?.cursor&&body.cursor!==cursor){refreshes.push({old:cursor,next:body.cursor});cursor=body.cursor;continue}if(result?.status===200&&body&&typeof body==='object')break;await sleep(1000*(a+1));
   }
   if(result?.status!==200||!body||typeof body!=='object')throw Error('Historical search fetch failed at page '+page);
   const entries=body.tweets&&typeof body.tweets==='object'?Object.keys(body.tweets):[],next=typeof body.cursor==='string'?body.cursor:null,rs=rowsFrom(body,page);
   const outOfRange=rs.filter(r=>r.published_at&&(r.published_at<'2025-03-03T00:00:00.000Z'||r.published_at>='2025-04-17T00:00:00.000Z')).map(r=>r.id);
   await save('historical_search',page,original,next,{response:body,http:result.status,refreshes},rs,{cursor_refreshes:refreshes.length,out_of_window_ids:outOfRange,source_exhausted:entries.length===0&&!next});processed++;
   if(!entries.length){stopReason=next?'empty_search_page_unverified':'search_exhausted';break}if(!next){stopReason='search_exhausted';break}if(seen.has(next)){stopReason='repeated_search_cursor';break}seen.add(next);cursor=next;await sleep(200);
  }
  return Response.json({newPosts,storedPosts:total,processedPages:processed,lastPage,lastDate,stopReason,query:QUERY,elapsedMs:Date.now()-began,fullHistoryVerified:false},{headers:H});
 }catch(e){return Response.json({error:safe(e),newPosts,storedPosts:total,processedPages:processed,lastPage,lastDate,stopReason,elapsedMs:Date.now()-began},{status:502,headers:H})}finally{for(const p of pending.values())clearTimeout(p.timer);pending.clear();try{ws?.close()}catch{}}
}
